<?php echo $this->doctype();?>
<html>
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>
<body class="bd_devices_sair bd_sair">
	<?php echo $this->render("includes/header.phtml"); ?>

<div class="ch-container">
	<div class="row">
   
    <!-- left menu starts -->
	<?php echo $this->render("includes/menu.phtml"); ?>
	<?php echo $this->render("includes/hidden.phtml"); ?>
	<div id="content" class="col-lg-12 col-sm-12 push">
		<?php
			$crumb = array("Home" => $this->baseUrl,
					"Apps" => "active",
					"S Air" => "active",
					"Devices" => "active");
			$array = array(
					"item" => $crumb,
					"class" => "col-lg-12",
					"style" => "padding-right:15px"
					);
			echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
		?>
		
		<!-- Content Placed here -->
		<div class="col-sm-12">
		<div class="panel panel-default">
		  <div class="panel-body" style="padding:0;margin:0">
				<h3>&nbsp;&nbsp;<?php echo $this->attr->title; ?></h3><hr/>
				<div class="form-group pull-right form-inline" style="margin-right:15px;">
					<div class="btn-group" style="position:relative;top:-70px;margin:0" id="export_csv">
						<button id="export" class="btn btn-default pull-right"><i class="glyphicon glyphicon-folder-open"></i> &nbsp;Export CSV</button>
					</div>
				</div>
				<div id="container" style="margin-top:0"></div>
		  </div>
		</div>
		
		<div class="panel panel-default">
			<div class="panel-body" style="padding:0;margin:0">
			<table class="table" id="slime_install">
				<thead>
				<tr>
					<th class="text-center"><h4><b>TOTAL INSTALL</b></h4></th>
					<th class="text-center"><h4><b>TOTAL DEVICE</b></h4></th>
				</tr>
				<thead>
				<tbody>
					<tr>
					
					</tr>
				</tbody>
			</table>
			</div>
		</div>
		
		<div class="panel panel-default">
			<div class="panel-body" style="padding:0;margin:0">
			<div class="table-container">
				<table class="table" id="slime_daily_install">
					<thead>
					<tr style="text-align:left;">
						<td>Device Name</td>
						<td>Total Install</td>
						<td>Segment</td>
					</tr>
					<thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
		</div>
		
		</div>

		</div>
	</div>
</div>
	<div class="bg-loading">
	<div class="loading">
		<div class="progress">
			<div class="progress-bar progress-bar-striped active"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
			</div>
		</div>
		</div>
		</div>
</body>
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/sair/sair_devices.js"); ?>