<?php echo $this->doctype();?>
<html ng-app="myAppSgift">
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>
<body class="bd_g_sgift bd_redeem" ng-controller="searchCrtl">
{{ff()}}
	<?php echo $this->render("includes/header.phtml"); ?>
	<?php echo $this->render("includes/hidden.phtml"); ?>
	<div class="ch-container">
	<div class="row">
	<!-- left menu starts -->
	<?php echo $this->render("includes/menu.phtml"); ?>
	<div id="content" class="col-lg-12 col-sm-12 push">
		<?php
			$crumb = array("Home" => $this->baseUrl,
							"Merchant" => "active",
							"Claim &amp; Redeem" => "active");
			$array = array(
							"item" => $crumb,
							"class" => "col-lg-7",
							"style" => "padding-right:0px"
							);
			echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
		?>

		<div class="col-lg-5" id="search-crumb" style="padding-left:0px;">
			<div class="col-lg-8 pull-right" id="search_container" style="padding-right:0px; padding-left:5px;">
				<form action="<?php echo $this->baseUrl;?>/merchant/redeem" method="GET" role="form" id="search-form">
					<div class="input-group">
					<span class="input-group-btn">
						<button type="button" class="btn btn-default search-btn" type="button" id="advanced_search_button">
						<span class="caret"></span><span class="sr-only">Toggle Dropdown</span>
						</button>
					</span>
					<input type="text" class="form-control" placeholder="Search.." name="q" id="input_search" value="<?php echo $this->param->q;?>">
					<span class="input-group-btn">
						<button class="btn btn-default" type="submit" ><span class="glyphicon glyphicon-search"></span></button>
					</span>
					</div><!-- /input-group -->
				</form>
			</div><!-- /.col-lg-4 col-lg-push-4-->
			
			<div class="btn-group pull-right" id="export_csv">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
					<span class="glyphicon glyphicon-folder-open"></span> &nbsp; Export CSV &nbsp;&nbsp; <span class="caret"></span>
				</button>
				<ul class="dropdown-menu" role="menu">
					<li><a ng-click="exportCurrent($event)" href="#">Export Current Document</a></li>
					<li><a ng-click="exportAll($event)" href="#">Export All</a></li>
					<li><a ng-click="exportClaim($event,'offline')" href="#">Export All Offline Claim</a></li>
					<li><a ng-click="exportClaim($event,'online')" href="#">Export All Online Claim</a></li>
				</ul>
			</div>
		</div>
		
		<div class="col-lg-6" >
			<div class="advanced_search_container col-sm-10" id="advanced_search_container">
			<div class="panel panel-default">
			<div class ="panel-body" >
				<h3>Advance Search</h3><hr/>
				<form action="<?php echo $this->baseUrl;?>/merchant/redeem" method="GET" role="form" class="form-horizontal" id="advance-search-form">
				<div class="form-horizontal">
					<div class="advanced-input-group">
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Promo ID</label>
							<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" id="promo_id" placeholder="Promo ID" name="promo_id" value="<?php echo $this->param->promo_id;?>">
							</div>
						 </div>
						<?php	if($this->mySession->role != $this->config->role->id->merchant) :?>
						  <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Merchant</label>
							<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" id="merchant_name" placeholder="Merchant Name" name="merchant_name" value="<?php echo $this->param->merchant_name;?>">
							</div>
						 </div>
						<?php endif; ?>
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Type</label>
							<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" id="type" placeholder="Type" name="type" value="<?php echo $this->param->type;?>">
							</div>
						 </div>		
						<?php if($this->mySession->role != $this->mySession->role->id->merchant) :?>
							 <div class="form-group">
								<label for="inputEmail3" class="col-sm-3 control-label">Channel</label>
								<div class="col-sm-9">
									<input type="text" class="form-control advanced-input" id="channel" placeholder="Channel" name="channel" value="<?php echo $this->param->channel;?>">
								</div>
							 </div>		
						<?php endif; ?>		
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Voucher</label>
							<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" id="voucher_id" placeholder="Voucher ID" name="voucher_id" value="<?php echo $this->param->voucher_id;?>">
							</div>
						 </div>						 
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Coupon Title</label>
							<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" id="promo_name" placeholder="Coupon Title" name="promo_name" value="<?php echo $this->param->promo_name;?>">
							</div>
						 </div>
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Claim Date</label>
							<div class="col-sm-9">
								<input type="text" class="form-control inline date"  name="start_claim" id="start_claim" value="<?php echo $this->param->start_claim; ?>" placeholder="YYYY-MM-DD" style="width:48%" /> 
								-
								<input type="text" class="form-control inline date" style="width:48%" name="end_claim" value="<?php echo $this->param->end_claim; ?>" placeholder="YYYY-MM-DD" id="end_claim" />
							</div>
						 </div>
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Redeem Date</label>
							<div class="col-sm-9">
								<input type="text" class="form-control inline date"  name="start_redeem" id="start_redeem" value="<?php echo $this->param->start_redeem; ?>" placeholder="YYYY-MM-DD" style="width:48%" /> 
								-
								<input type="text" class="form-control inline date" style="width:48%" name="end_redeem" value="<?php echo $this->param->end_redeem; ?>" placeholder="YYYY-MM-DD" id="end_redeem" />
							</div>
						 </div>
						<button class="btn btn-primary search-btn pull-right" id="adv-button"><span class="glyphicon glyphicon-search"></span> &nbsp;Search</button>
					</div>
					</div>
				</form>
				</div>
				</div>
			</div>
		</div>
		
		<div class="col-sm-12">
			<div class="panel panel-default">
			<div class="panel-body">				
			<div class="row">
			<!-- Popup -->
			<div class="panel panel-primary promo_detail_container">
			  <div class="panel-heading">
			  <button type="button" class="close white" data-dismiss="modal" id="close_promo"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h3 class="panel-title">Promo Detail</h3>
			  </div>
			  <div class="panel-body" id="detail_promo">
				Panel content
			  </div>
				<table class="table table-bordered promo_table table-striped"  >
					<thead>
						<tr>
							<th>Total Coupon</th>
							<th>Total Redeem</th>
							<th>Remaining Redeem</th>
							<th>Total Claim</th>
							<th>Remaining Claim</th>
						</tr>
					</thead>
					<tbody id="promo_number">
						<tr>
						</tr>
					</tbody>
				  </table>
			</div>
			<div class="panel panel-primary user_detail_container">
				<div class="panel-heading">
					<button type="button" class="close" data-dismiss="modal" id="close_user"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h3 class="panel-title">User Details</h3>
				</div>
				<div class="panel-body" id="detail_user">
					Panel content
				</div>
			</div>
			<!-- -->
			
			<div class="form-group pull-left form-inline" style="margin-left:15px;">
				<form class="form-inline" role="form">
				<span class="pull-left lbl"><h5>&nbsp; <i class="glyphicon glyphicon-eye-open"></i> &nbsp;Showing &nbsp;<strong>{{search_list.length | number:0}}</strong>&nbsp; from 
				&nbsp;<strong>{{totalData | number:0}}</strong>&nbsp; data</h5></span>
				</form>
			</div>
			
			<div class="form-group pull-right form-inline" style="margin-right:15px;">	
				<div class="form-group" id="filter-textbox">
					<div class="input-group ">
					  <div class="input-group-addon">
						<span class="glyphicon glyphicon-filter"></span>&nbsp;&nbsp;<span class="badge">{{filtered.length | number:0}}</span>
					  </div>
					  <input class="form-control" ng-model="query[queryBy]" placeholder="Type the filter here.." >
					</div>
				</div>
				
				<div class="form-group" id="filter-option">
					<select class="form-control" ng-model="queryBy">
						<option value="$">All</option>
						<option value="promo_id">Promo ID</option>
						<?php if(!$this->mySession->role == $this->config->role->id->aggregator) :?>
						<option value="channel">Channel</option>
						<?php endif; ?>
						<?php if(!$this->mySession->role != $this->config->role->id->merchant) :?>
						<option value="merchant_name">Merchant</option>
						<?php endif; ?>
						<option value="promo_name">Coupon Title</option>
						<option value="claim_type">Type</option>
						<option value="voucher_id">Voucher</option>
					</select>		
				</div>
			</div>
			<br/>

			</div><!-- /.row -->

			</form>
			<div class="clear"></div>
			<div class='tb-test'>
			<div class="t-c">
				<?php 
					$size = ($this->mySession->role != $this->config->role->id->merchant) ? "11%" : "14%";
					$headSize = ($this->mySession->role != $this->config->role->id->merchant) ? "300px" : "350px";
				?>
				<table class="table table-striped" id="transaction_table" >	
					<thead>
					<tr>
						<th width="<?php echo $headSize; ?>"><a ng-click="sort_by('promo_id')"><button class="sort_tool">Promo ID <span class="caret"></span></button></a></th>
						
						<?php if($this->mySession->role != $this->config->role->id->merchant) :?>
							<th width="<?php echo $size; ?>" style="text-align:center"><a ng-click="sort_by('channel')"><button class="sort_tool">Channel <span class="caret"></span></button></a></th>
						<?php endif; ?>
						
						<th width="<?php echo $size; ?>"><a ng-click="sort_by('redeem_time | asDate');"><button class="sort_tool">Redeem <span class="caret"></span></button></a></th>
						<th width="<?php echo $size; ?>"><a ng-click="sort_by('claim_time | asDate');"><button class="sort_tool">Claim <span class="caret"></span></button></a></th>
						
						<?php if($this->mySession->role != $this->config->role->id->merchant) :?>						
							<th width="<?php echo $size; ?>"><a ng-click="sort_by('merchant_name')"><button class="sort_tool">Merchant <span class="caret"></span></button></a></th>
						<?php endif; ?>
						
						<th width="<?php echo $size; ?>"><a ng-click="sort_by('promo_name');"><button class="sort_tool">Coupon Title <span class="caret"></span></button></a></th>
						<th width="<?php echo $size; ?>" style="text-align:center"><a ng-click="sort_by('claim_type');"><button class="sort_tool">Type <span class="caret"></span></button></a></th>
						<th width="<?php echo $size; ?>" style="text-align:center"><a ng-click="sort_by('voucher_id');"><button class="sort_tool">Voucher <span class="caret"></span></button></a></th>
						<th width="<?php echo $size; ?>" style="text-align:center"><a ng-click="sort_by('outlet_name');"><button class="sort_tool">Store <span class="caret"></span></button></a></th>
						<th width="1%"></th>
					</tr>
					</thead>	
					
					<tbody scroll>
						<tr ng-repeat="x in filtered = ( search_list | filter:query | filter:queryByDay | filter:queryByPickerDay ) | orderBy:predicate:reverse ">
							<td width="<?php echo $headSize; ?>">{{ x.promo_id }}</td>
					
							<?php if($this->mySession->role != $this->config->role->id->merchant) : ?>
							<td align="center" width="<?php echo $size; ?>">{{ x.channel}}</td>
							<?php endif;?>
							
							<td width="<?php echo $size; ?>">{{ x.redeem_time | asDate | date:'dd MMM yyyy - HH:mm'}}</td>
							<td width="<?php echo $size; ?>" >&nbsp;&nbsp;{{ (x.claim_time==null)?'-': (x.claim_time | asDate | date:'dd MMM yyyy - HH:mm')}}</td>							
						
							<?php if($this->mySession->role != $this->config->role->id->merchant) :?>	
							<td width="<?php echo $size; ?>" ng-bind-html="trustHtml(x.merchant_name)"></td>
							<?php endif; ?>
							<td width="<?php echo $size; ?>" ng-bind-html="trustHtml(x.promo_name)"></td>
							<td width="<?php echo $size; ?>" align="center">{{ x.claim_type }} 	</td>
							<td width="<?php echo $size; ?>" align="center">{{ x.voucher_id }}</td>							
							<td width="<?php echo $size; ?>" align="center">{{ (x.outlet_name==null)?'-':(x.outlet_name) }}</td>
						</tr>
					</tbody>
				</table>
			</div>
				
			<div class="bg-loading">
			<div class="loading-text">
				<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="25px" height="25px"/>  &nbsp; &nbsp; <b>Loading...</b>
			</div>
			</div>	

			</div>
			<center>
			<div class="bg-log-loading" style="display:block">
				<div class="loading-text">
					<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="75px" height="75px"/><br/><h3><b>Loading...</b></h3>
				</div>
			</div>
			</center>
			</div>
		</div>
		</div>
	</div>
	<!-- Cover -->
	<div class="cover"></div>
	</body>	
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/merchant/redeem.js"); ?>