<?php echo $this->doctype();?>
<html ng-app=EmployeeApp>
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>
<body class="bd_log" ng-controller="empCtrl">
	<?php echo $this->render("includes/header.phtml"); ?>
	<?php echo $this->render("includes/hidden.phtml"); ?>
	<div class="ch-container">
		<div class="row">
		<!-- left menu starts -->
		<?php echo $this->render("includes/menu.phtml"); ?>
		<div id="content" class="col-lg-12 col-sm-12 push">
			<?php
				$crumb = array("Home" => $this->baseUrl,
							   "Management" => "active",
							   "User Logs" => "active");
				$array = array(
								"item" => $crumb,
								"class" => "col-lg-7",
								"style" => "padding-right:0px"
							  );
				echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
			?>
			
			<div class="col-lg-5" id="search-crumb" style="padding-left:0px;">
				<div class="col-lg-8 pull-right" id="search_container" style="padding-right:0px; padding-left:5px;">
					<form action="<?php echo $this->baseUrl;?>/log" method="GET">
						<div class="input-group">
						<span class="input-group-btn" style="width:40px;">
							<button class="btn btn-default search-btn" style="width:100%" type="button" id="advanced_search_button">
								<!--<span class="glyphicon glyphicon-cog"></span>-->
								<span class="caret"></span>
							</button>
						</span>
						<input type="text" class="form-control" placeholder="Search..." name="q" id="input_search" value="<?php echo $this->param->q;?>" />
						<span class="input-group-btn">
							<button class="btn btn-default" type="submit" ><span class="glyphicon glyphicon-search"></span></button>
						</span>
						</div><!-- /input-group -->
					</form>
				</div><!-- /.col-lg-4 col-lg-push-4-->
				
				<div class="btn-group pull-right" id="export_csv">
					<button id="export" class="btn btn-default"><i class="glyphicon glyphicon-folder-open"></i> &nbsp;Export CSV</button>
				</div>
			</div>
			
			<div class="col-sm-6">			
			<div class="advanced_search_container col-sm-10" id="advanced_search_container" >
				<div class="panel panel-default">
				<div class ="panel-body" >
					<h3>Advance Search</h3><hr/>
					<form action="<?php echo $this->baseUrl;?>/log" method="GET" role="form" class="form-horizontal">
					<div class="form-horizontal">
					<div class="advanced-input-group">
					<div class="form-group">
					<label for="inputEmail3" class="col-sm-3 control-label">Username</label>
					<div class="col-sm-9">
					<input type="text" class="form-control advanced-input" placeholder="Username" name="username" value="<?php echo $this->param->username;?>">
					</div>
					</div>
					<div class="form-group">
					<label for="inputEmail3" class="col-sm-3 control-label">Role</label>
					<div class="col-sm-9">
						<select id="role" name="role" class="form-control">
							<option value="">- All Role -</option>
							<?php foreach ($this->roleList as $role) : ?>
							<option value="<?php echo $role->roleID;?>"
							<?php echo ($role->roleID == $this->param->role) ? "selected" : ""; ?>
							><?php echo $role->roleName;?></option>
							<?php endforeach;?>
						</select>
					</div>
					</div>
					<!-- <div class="form-group">
					<label for="inputEmail3" class="col-sm-3 control-label">Created Date</label>
					<div class="col-sm-9">
					<input type="text" class="form-control advanced-input date" placeholder="Created Date" name="created_date" value="<?php echo $this->param->created_date;?>">
					</div>
					</div> -->
					
					<div class="form-group">
					<label for="inputEmail3" class="col-sm-3 control-label">Activity</label>
					<div class="col-sm-9">
					<input type="text" class="form-control advanced-input" placeholder="Activity Name" name="activity" value="<?php echo $this->param->activity;?>">
					</div>
					</div>
					<div class="form-group">
					<label for="inputEmail3" class="col-sm-3 control-label">Details</label>
					<div class="col-sm-9">
					<input type="text" class="form-control advanced-input" placeholder="Detail Activity" name="detail" value="<?php echo $this->param->detail;?>">
					</div>
					</div>
					<div class="form-group">
						<label for="inputEmail3" class="col-sm-3 control-label">Activity Time</label>
						<div class="col-sm-9">
							<input type="text" class="form-control inline date"  name="start_date" id="start_date" value="<?php echo $this->param->start_date; ?>" placeholder="YYYY-MM-DD" style="width:48%" /> 
							-
							<input type="text" class="form-control inline date" style="width:48%" name="end_date" value="<?php echo $this->param->end_date; ?>" placeholder="YYYY-MM-DD" id="end_date" />
						</div>
					 </div>
					<button type="submit" class="btn btn-primary search-btn pull-right"><i class="glyphicon glyphicon-search"></i> &nbsp;Search</button>
					</div>
					</div>
					</form>
				</div>
				</div>
			</div>
			</div>
			
			<div class="col-sm-12">
				<div class="panel panel-default">
				<div class="panel-body">
					
					<div class="form-group pull-left form-inline" style="margin-left:0px;">
						<span class="pull-left lbl"><h5>&nbsp; <i class="glyphicon glyphicon-eye-open"></i> &nbsp;Showing &nbsp;<strong>{{employees.length | number:0}}</strong>&nbsp; from 
						&nbsp;<strong><?php echo number_format($this->totalLog,0,".",","); ?></strong>&nbsp; data</h5></span>
					</div>
					
					<div class="form-group pull-right form-inline" style="margin-right:0px;">
						<div class="form-group ">
							<div class="input-group ">
							  <div class="input-group-addon">
								<span class="glyphicon glyphicon-filter"></span>&nbsp;&nbsp;<span class="badge">{{filtered.length | number:0}}</span>
							  </div>
							  <input class="form-control" ng-model="query[queryBy]" placeholder="Search">
							</div>
						</div>
						<div class="form-group">
							<select class="form-control" ng-model="queryBy">
								<option value="$">All</option>
								<option value="username">Username</option>
								<option value="roleName">Role</option>
								<option value="created_date">Activity Time</option>
								<option value="activity_name">Activity Name</option>
								<option value="detail_activity">Detail</option>
							</select>
						</div>
						
						<div class="btn-group">
							<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
								<span class="glyphicon glyphicon-time"></span>&nbsp;&nbsp;<span class="caret"></span>
							</button>
							<ul class="dropdown-menu" role="menu">
								<li><a id="btall" ng-click="start_date=''; end_date=''; Range = ''" value="all" href="#">All</a></li>
								<li><a id="bt7days" ng-click="start_date=''; end_date=''; Range = 7" value="7days" href="#">7 Days</a></li>
								<li><a id="bt30days" ng-click="start_date=''; end_date=''; Range = 30" value="30days" href="#">30 Days</a></li>
							</ul>
						</div>
						
						<!-- <div class="btn-group">	
							<button class="btn btn-default" type="button" id="start_date_btn" data-toggle="dropdown"><span class="glyphicon glyphicon-calendar"></span> </button>
									<div class="date_dropdown pull-right dropdown-menu" role="menu">
								<div class="row">
									<div class="col-md-6">
										<div id="datepicker1"></div>
									</div>
									<div class="col-md-6">
										<div id="datepicker2"></div>
									</div>
								</div>
								<div class="row">
								
									<div class="col-md-12">
										<button class="btn btn-default pull-right" id="apply_date" type="button" ng-click="applyDate($event)">Apply</button>
								</div>
								</div>
							</div>	
							
						</div> -->
					</div>

					<div class="clear"></div>
					
					<div>
					<div class='tb-test'>
						<table class="table table-striped" id="log_table">	
							<thead>
								<tr>
									<th width="16%"><a href="#" ng-click="predicate = 'username'; reverse=!reverse"><button class="sort_tool">Username</button></a></th>
									<th width="16%"><a href="#" ng-click="predicate = 'roleName'; reverse=!reverse"><button class="sort_tool">Role</button></a></th>
									<th width="16%" style="text-align:center;"><a href="#" ng-click="predicate = 'created_date | asDate'; reverse=!reverse"><button class="sort_tool">Activity Time</button></a></th>
									<th width="16%" style="text-align:center;"><a href="#" ng-click="predicate = 'activity_name'; reverse=!reverse"><button class="sort_tool">Activity name</button></a></th>
									<th width="700px"><a href="#" ng-click="predicate = 'detail_activity'; reverse=!reverse"><button class="sort_tool">Details</button></a></th>
								</tr>
							</thead>
							<tbody scroll>
								<tr ng-repeat="emp in filtered = ( employees | filter:query | filter:queryFilter ) | orderBy:predicate:reverse">
									<td width="16%">{{emp.username}}</td>
									<td width="16%">{{emp.roleName}}</td>
									<td width="16%" align="center">{{emp.created_date | asDate | date:'dd MMM yyyy - HH:mm'}}</td>
									<td width="16%" align="center">{{emp.activity_name}}</td>
									<td width="700px">{{emp.detail_activity}}</td>
								</tr>
							</tbody>
						</table>
						
						<div class="bg-loading">
						<div class="loading-text">
							<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="25px" height="25px"/>  &nbsp; &nbsp; <b>Loading...</b>
						</div>
						</div>	
					</div>
					<center>
					<div class="bg-log-loading">
						<div class="loading-text">
							<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="75px" height="75px"/><br/><h3><b>Loading...</b></h3>
						</div>
					</div>
					</center>	
					</div>
				</div>
				</div>
			</div>
		</div>
	</div>
	</body>
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/log.js"); ?>