<?php echo $this->doctype();?>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>

<body class="bluback">
	<br/><br/><br/>
	<div class="logo-container">
	<center>
	<img src="<?php echo $this->baseUrl;?>/assets/images/samsung-white-lg.png" class="img-responsive logo-login" onload="$(this).fadeIn();"  alt="Samsung Logo"/>
	</center>
	</div>

	<div class="col-lg-offset-4 col-lg-4 col-md-offset-4 col-md-4 col-sm-offset-3 col-sm-6" id="frmlogin">
	<br/><br/>
	
	<div class="col-lg-12">
	<div class="panel panel-primary login-panel">
		
		<div class="panel-body">
			<h2 class="text-center">Login</h2>
			<div class="border-grey"></div><div class="clear"></div>
			<div class="border-white"></div><div class="clear"></div>

			<form class="form-horizontal" role="form" method="post" action="<?php echo $this->baseUrl; ?>/index/chklogin">
				<div class="form-group">
					<label class="input-group col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-offset-1 col-lg-10 col-xs-offset-1 col-xs-10">
					<font color="#4385cb"><h5><b>Username</b></h5></font>
					</label>
					<div class="input-group col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-offset-1 col-lg-10 col-xs-offset-1 col-xs-10">
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-user"></span>
						</span>
						<input type="email" class="form-control" name="username" id="inputUsername" placeholder="Username" maxlength="50" />
					</div>
				</div>
				
				<div class="form-group">
					<label class="input-group col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-offset-1 col-lg-10 col-xs-offset-1 col-xs-10">
					<font color="#4385cb"><h5><b>Password</b></h5></font>
					</label>
					<div class="input-group col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-offset-1 col-lg-10 col-xs-offset-1 col-xs-10">
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-lock"></span>
						</span>
						<input type="password" class="form-control" name="password" id="inputPass" placeholder="Password" maxlength="30" />
					</div>
				</div>
				
			
				<br/>
				<div class="form-group">
					<label for="inputUsername" class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
						<a href="#forget_pass" data-toggle="modal" id="lnkforget"><h5><b>Forgot Password</b></h5></a>
					</label>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-right">
					  <button type="submit" class="btn btn-default btn-lg" value="submit"><i class="glyphicon glyphicon-log-in"></i> &nbsp;Login</button>
					</div>
				</div>
				
				<!--<div class="form-group text-left">
					<div class=" col-lg-4 col-md-4 col-sm-4 col-xs-4">
					  <button type="submit" class="btn btn-primary btn-lg" value="submit"><i class="glyphicon glyphicon-log-in"></i> &nbsp;Login</button>
					</div>
				</div>-->
			</form>
			
			<div class="form-group">
				<label for="inputUsername" class="col-sm-7 col-lg-7 col-md-7 col-xs-7 control-label">
					<font color="red"><?php echo $this->error;?></font>
				</label>
			</div>
		</div>
	</div>
	</div>
	
	</div>
	
	<!-- <div class="modal fade" id="forget_pass" role="dialog"> -->
	<div class="col-lg-offset-4 col-lg-4 col-md-offset-4 col-md-4 col-sm-offset-3 col-sm-6" id="form_forget">
	<br/><br/>
	
	<div class="col-lg-12">
		<div class="panel panel-primary login-panel">
			<div class="panel-body">
				<h2 class="text-center">Forgot Password</font></h2>
				<div class="border-grey"></div><div class="clear"></div>
				<div class="border-white"></div><div class="clear"></div>
				
				<form class = "form-horizontal">
					<div class="form-group">
						<label class="input-group col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-offset-1 col-lg-10 col-xs-offset-1 col-xs-10">
						<font color="#4385cb"><h5><b>Username</b></h5></font>
						</label>
						<div class="input-group col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-offset-1 col-lg-10 col-xs-offset-1 col-xs-10">
							<span class="input-group-addon">
								<span class="glyphicon glyphicon-user"></span>
							</span>
							<input type="email" class="form-control" name="forget_username" id="forget_username" placeholder="Username" maxlength="30" />
						</div>
					</div>
					
					<div class="form-group">
						<label for="inputUsername" class="col-sm-offset-1 text-center col-sm-10 col-lg-10 col-md-10 col-xs-10 control-label">
							<font color="red" id="fterror"></font><br/>
						</label>
					</div>
					
					<div class="form-group text-right">
						<div class="col-md-11 col-lg-11 col-sm-11 col-xs-11">
						<button type="button" class="btn btn-default" id="btback_login" data-dismiss="modal"><b>Back</b></button>
						<button type="button" class="btn btn-primary" id="reset_password"><b>Reset Password</b></button>
						</div>
					</div>
				</form>		
				<br>
			</div>	
		</div>
		</div>
		
	</div>
	<!-- </div> -->
</body>
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/login.js"); ?>
