<html>
  <head>
    <title>Form Login</title>
  </head>
  <body bgcolor="#B5B5B5">
    <center>
      <h1>myInterns</h1>
      <div style="border: 2px solid; border-radius: 25px; background-color:#E8E8E8; height:150px; width:500px; padding: 100px;" >
        <form action="<?php echo $this->baseUrl; ?>/index/dologin" method="POST">
          <table cellpadding="15">
            <tr>
              <td>Username</td>
              <td><input type="text" name="txtuser" /></td>
            </tr>
            <tr>
              <td>Password</td>
              <td><input type="password" name="txtpass" /></td>
            </tr>
            <?php if(isset($this->error)): ?>
              <tr>
                <td colspan=2 style="color: red; text-align:center;"><?php echo $this->error; ?></td>
              </tr>
            <?php endif; ?>
            <tr>
              <td colspan=2><center><input type="submit" value="Submit" /><input type="reset" value="Reset" /></center></td>
            </tr>
          </table>
        </form>
		<a href ="<?php echo $this->baseUrl ?>/register/index">Register</a>
      </div>
    </center>
  </body>
</html>
