<?php echo $this->doctype();?>
<html>
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>
<body class="bd_g_sgift bd_chartbase">
	<?php echo $this->render("includes/header.phtml"); ?>
	<div class="d_none" id="activeMonthly"><?php echo $this->activeMonthlyTemp; ?></div>
	<div class="d_none" id="activeWeekly"><?php echo $this->activeWeeklyTemp; ?></div>
	<div class="d_none" id="activeDaily"><?php echo $this->activeDailyTemp; ?></div>
	<div class="ch-container">
		<div class="row">
	   
		<!-- left menu starts -->
		<?php echo $this->render("includes/menu.phtml"); ?>
		
		<div id="content" class="col-lg-12 col-sm-12 push">
			<?php
				$crumb = array("Home" => $this->baseUrl,
							   "Dashboard" => "active",
							   "Claim & Redeem chart" => "active");
				$array = array(
								"item" => $crumb,
								"class" => "col-lg-7",
								"style" => "padding-right:0px"
							  );
				echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
			?>
			<div class="col-lg-5" id="search-crumb" style="padding-left:0px;">
			
				<div class="col-lg-12 pull-right" id="search_container" style="padding-right:0px; padding-left:5px;">
				<button class="btn btn-default chart_btn filter">Filter</button>		
				 <div class="btn-group">
				<button type="button" id="daily" class="btn btn-default chart_btn">Daily</button>	
				<button type="button" id="week" class="btn btn-default filter-chart" data-val="week">Week</button>	
				<button type="button" id="month" class="btn btn-default filter-chart" data-val="month">Month</button>	
			</div>
					<div class="col-sm-7">
						<select id="promo" name="role" class="form-control filter">
						<option value="">- All Promo -</option>
					<?php
						foreach($this->promos as $promo):
					?>
							
							<option value="<?php echo $promo->promo_id;?>"
							<?php echo ($promo->promo_id == $this->param->promo_id) ? "selected" : ""; ?>
							><?php echo $promo->name;?></option>

					<?php
						endforeach;
					?>
						</select>
					</div>
					
						 
				</div>
			</div>
			<div class="col-lg-12">
			<div class="col-sm-12">
				<div class="panel panel-default container custom" id="chart" style="display:block;">
				<div class="panel-body">

					<div id="container" ></div>
					<div class="bg-loading-segment">
					</div>	
					<div class="loading-circle">
						<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="25px" height="25px"/>  &nbsp; &nbsp; <b>Loading...</b>
					</div>	
				</div>
				</div>
				</div>
			</div> <!--col-sm-12 close -->
		</div> <!--content close -->
	</div> <!-- ch-container close -->
</body>
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/dashboard/chart2.js"); ?>