<?php echo $this->doctype();?>
<html ng-app="myAppSlime">
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>
<body class="bd_g_slime bd_publisher_content" ng-controller="searchCrtl">
<!--{{ff()}} -->
	<?php echo $this->render("includes/header.phtml"); ?>
	<?php echo $this->render("includes/hidden.phtml"); ?>
	<div class="ch-container">
	<div class="row">
	   
	<!-- left menu starts -->
	<?php echo $this->render("includes/menu.phtml"); ?>
			
	<div id="content" class="col-lg-12 col-sm-12 push">
		<?php
			$crumb = array("Home" => $this->baseUrl,
					"S Lime" => "active",
					"Uploaded Content" => "active");
			$array = array(
					"item" => $crumb,
					"class" => "col-lg-7",
					"style" => "padding-right:0px"
					);
			echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
		?>
		
		<div class="col-lg-5" id="search-crumb" style="padding-left:0px;">
			<div class="col-lg-8 pull-right" id="search_container" style="padding-right:0px; padding-left:5px;">
				<form action="<?php echo $this->baseUrl;?>/publisher/content" method="GET" role="form" id="search-form">
					<div class="input-group">
					<span class="input-group-btn">
						<button class="btn btn-default search-btn" type="button" id="advanced_search_button"><span class="caret"></span></button>
					</span>
					<input type="text" class="form-control" placeholder="Search.." name="q" id="input_search" value="<?php echo $this->param->q;?>">
					<span class="input-group-btn">
						<button class="btn btn-default" type="submit" ><span class="glyphicon glyphicon-search"></span></button>
					</span>
					</div><!-- /input-group -->
				</form>
			</div><!-- /.col-lg-4 col-lg-push-4-->
			
			<div class="btn-group pull-right" id="export_csv">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
					<span class="glyphicon glyphicon-folder-open"></span> &nbsp; Export CSV &nbsp;&nbsp;<span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu" role="menu">
					<li><a ng-click="exportCurrent($event)" href="#">Export Filtered Data</a></li>
					<li><a ng-click="exportAll($event)" href="#">Export All</a></li>
				  </ul>
			</div>
		</div>
		
		<div class="col-lg-6" >
			<div class="advanced_search_container col-sm-10" id="advanced_search_container">
			<div class="panel panel-default">
			  
			<div class ="panel-body" >
				<h3>Advance Search</h3><hr/>
				<form action="<?php echo $this->baseUrl;?>/publisher/content" method="GET" role="form" class="form-horizontal" id="advance-search-form">
				<div class="form-horizontal">
					<div class="advanced-input-group">
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Product Name</label>
							<div class="col-sm-9">
							  <input type="text" class="form-control advanced-input" placeholder="Product Name.." name="product_name" id="product_name" value="<?php echo $this->param->product_name;?>">
							</div>
						 </div>
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Category</label>
							<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" placeholder="Category.." name="category" id="category" value="<?php echo $this->param->category;?>">
							</div>
						 </div>
						 						 
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Publisher Name</label>
							<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" placeholder="Publisher Name.." name="publisher" id="publisher" value="<?php echo $this->param->publisher;?>">
							</div>
						 </div>
						 
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Publication Group</label>
							<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" placeholder="Group.." name="group" id="group" value="<?php echo $this->param->group;?>">
							</div>
						 </div>
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Release Date</label>
							<div class="col-sm-9">
								<input type="text" class="form-control inline date"  name="start_release" id="start_release" value="<?php echo $this->param->start_release; ?>" placeholder="YYYY-MM-DD" style="width:48%" /> 
								-
								<input type="text" class="form-control inline date" style="width:48%" name="end_release" value="<?php echo $this->param->end_release; ?>" placeholder="YYYY-MM-DD" id="end_release" />
							</div>
						 </div>
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Price</label>
							<div class="col-sm-9">
								<input type="text" class="form-control advanced-input num" placeholder="Price" name="price" id="price" value="<?php echo $this->param->price;?>">
							</div>
						 </div>
						 
						<button class="btn btn-primary search-btn pull-right" id="adv-button"><span class="glyphicon glyphicon-search"></span> &nbsp;Search</button>
					</div>
					</div>
				</form>
				</div>
				</div>
			</div>
		</div>
		
		<div class="col-sm-12">
			<div class="panel panel-default">
			
			<div class="panel-body">					
			<div class="row">
			
	
			<div class="panel panel-primary user_detail_container">
				<div class="panel-heading">
					<button type="button" class="close" data-dismiss="modal" id="close_user"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h3 class="panel-title">User Details</h3>
				</div>
				<div class="panel-body" id="detail_user">
					Panel content
				</div>
			</div>
			
			<!-- -->
			
			<div class="form-group pull-left form-inline" style="margin-left:15px;">
				<form class="form-inline" role="form">
				<span class="pull-left lbl"><h5>&nbsp; <i class="glyphicon glyphicon-eye-open"></i> &nbsp;Showing &nbsp;<strong>{{search_list.length | number:0}}</strong>&nbsp; from 
						&nbsp;<strong>{{totalData | number:0}}</strong>&nbsp; data</h5></span>
				</form>
			</div>
			
			<div class="form-group pull-right form-inline" style="margin-right:15px;">	
				
				<div class="form-group" id="filter-textbox">
					<div class="input-group ">
					  <div class="input-group-addon">
						<span class="glyphicon glyphicon-filter"></span>&nbsp;&nbsp;<span class="badge">{{filtered.length | number:0}}</span>
					  </div>
					  <input class="form-control" ng-model="query[queryBy]" placeholder="Filter by..." >
					</div>
				</div>
				<div class="form-group" id="filter-option">
					<select class="form-control" ng-model="queryBy">
						<option value="$">All</option>
						<option value="name">Product Name</option>
						<option value="category">Category</option>
						<option value="author">Publisher Name</option>
						<option value="group">Publication Group</option>
						<option value="release_date">Release Date</option>
						<option value="price">Price</option>
						<option value="download">Download Numbers</option>
					</select>		
				</div>
				
				&nbsp;
				<div class="btn-group">
					<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
						<span class="glyphicon glyphicon-time"></span>&nbsp;&nbsp;<span class="caret"></span>
					</button>
					<ul class="dropdown-menu" role="menu">
						<li><a id="btall" ng-click="DateRange = ''" value="all" href="#">All</a></li>
						<li><a id="bt7days" ng-click="DateRange = 7" value="7days" href="#">7 Days</a></li>
						<li><a id="bt30days" ng-click="DateRange = 30" value="30days" href="#">30 Days</a></li>
					</ul>
				</div>
			</div>	
			</div><!-- /.row -->

			<div class='tb-test'>
				<div class="pull-left">
				</div>
				<div class="t-c">
				<?php 
					$size =  "13";
					$headSize = "320px";
				?>
				<table class="table table-striped" id="transaction_table" >	
					<thead>
					<tr>
						<th width="<?php echo $headSize; ?>"><a ng-click="sort_by('name')"><button class="sort_tool">Product Name <span class="caret"></span></button></a></th>
						<th width="<?php echo $size."%"; ?>" style="text-align:center;"><a ng-click="sort_by('category')"><button class="sort_tool">Category <span class="caret"></span></button></a></th>
						<th width="<?php echo $size."%"; ?>" style="text-align:center"><a ng-click="sort_by('author')"><button class="sort_tool">Publisher Name <span class="caret"></span></button></a></th>
						<th width="<?php echo $size."%"; ?>" style="text-align:center"><a ng-click="sort_by('group')"><button class="sort_tool">Publication Group <span class="caret"></span></button></a></th>						
						<th width="<?php echo $size."%"; ?>" style="text-align:center;"><a ng-click="sort_by('release_date | asDate')"><button class="sort_tool">Release Date <span class="caret"></span></button></a></th>
						<th width="<?php echo $size."%"; ?>" style="text-align:center;"><a ng-click="sort_by('price')"><button class="sort_tool">Price <span class="caret"></span></button></a></th>
						<th width="<?php echo ($size-1)."%"; ?>" style="text-align:center;"><a ng-click="sort_by('download')"><button class="sort_tool">Download Numbers <span class="caret"></span></button></a></th>		
						<th width="<?php echo $size."%"; ?>" style="text-align:center;"><a ng-click="sort_by('trans')"><button class="sort_tool">Transaction <span class="caret"></span></button></a></th>								
					</tr>
					</thead>				
					<tbody scroll>
						<tr ng-repeat="x in filtered = ( search_list | filter:query | filter:queryByDay) | orderBy:predicate:reverse ">
							<td width="<?php echo $headSize; ?>" style="word-break:break-all;">
								<a href="#productBox" ng-click="showBook($event, x)" ng-bind-html="trustHtml(x.name + ' - ' + (x.release_date | asDate | date:'dd MMM yyyy')  )"></a>
							</td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center" ng-bind-html="trustHtml(x.category)"></td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center" ng-bind-html="trustHtml(x.author)"></td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center" ng-bind-html="trustHtml(x.group)"></td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center">{{x.release_date | asDate | date:'dd MMM yyyy'}}</td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center">{{x.price | number:0}},-</td>
							<td width="<?php echo ($size-1)."%"; ?>" style="text-align:center">
								<strong><a href="#downloadHistory" ng-click="showDownload($event, x)">
									{{ (x.download == null) ? 0 : x.download }}
								</a></strong>
							</td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center">
								<strong><a href="<?php echo $this->baseUrl; ?>/csslime?pid={{x.id}}&pname={{x.name}}" target="_new">
									{{ (x.trans == null) ? 0 : x.trans }}
								</a></strong>
							</td>
						</tr>
					</tbody>
				</table>
				
				</div>
					
				<div class="bg-loading">
					<div class="loading-text">
					<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="25px" height="25px"/>  &nbsp; &nbsp; <b>Loading...</b>
					</div>
				</div>	
			</div>
			<center>
			<div class="bg-log-loading" style="display:block">
				<div class="loading-text">
					<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="75px" height="75px"/><br/><h3><b>Loading...</b></h3>
				</div>
			</div>
			</center>
			</div>
		</div>
		</div>
	</div>
	<!-- Cover -->
	<div class="cover"></div>
	<?php echo $this->render("includes/publisher/download_history.phtml"); ?>
	<?php echo $this->render("includes/publisher/product_box.phtml"); ?>
	</body>	
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/publisher/content.js"); ?>