<!-- Device Box -->
<div class="modal fade" id="deviceBox">
  <div class="modal-dialog" style="width:855px">
    <div class="modal-content">
		<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h3><span class="glyphicon glyphicon-phone"></span>  &nbsp;Device (<span class="pname"></span>)</h3>
		</div>
		
		<div class ="modal-body" >
			<div class="form-horizontal">
				<div class="send_group">
				<table class="table table-striped" id="transaction_table" style="width:820px;" >	
					<thead>
					<tr>
						<th width="70px"><a ng-click="sort_c_by('$index')"><button class="sort_tool">No. <span class="caret"></span></button></a></th>
						<th width="188px"><a ng-click="sort_c_by('name')"><button class="sort_tool">Device Name <span class="caret"></span></button></a></th>
						<th width="188px" style="text-align:center"><a ng-click="sort_c_by('manufactur')"><button class="sort_tool">Manufacture <span class="caret"></span></button></a></th>
						<th width="188px"><a ng-click="sort_c_by('model')"><button class="sort_tool">Model <span class="caret"></span></button></a></th>
						<th width="188px"><a ng-click="sort_c_by('status')"><button class="sort_tool">Status <span class="caret"></span></button></a></th>					
					</tr>
					</thead>				
					<tbody scroll>
						<tr ng-if="deviceData.length <= 0">
							<td colspan="5" align="center">
								<span class="glyphicon glyphicon-exclamation-sign"></span> &nbsp;<strong>No Device Found...</strong>
							</td>
						</tr>
						<tr ng-repeat="data in deviceData | orderBy:predicate_c:reverse_c">
							<td width="70px" align="center">{{ $index+1 }}</td>
							<td width="188px">{{data.name}}</td>
							<td width="188px" align="center">{{data.manufactur}}</td>
							<td width="188px">{{data.model}} </td>
							<td width="188px">{{data.status}}</td>
						</tr>
					</tbody>
				</table>
				</div>
			</div>
		</div>
	</div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->