<!-- Device Box -->
<div class="modal fade" id="productBox">
  <div class="modal-dialog" style="width:955px">
    <div class="modal-content">
		<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h3><span class="glyphicon glyphicon-tags"></span>  &nbsp;Product (<span class="pname"></span>)</h3>
		</div>
		
		<div class ="modal-body" >
			<div class="form-horizontal">
				<div class="send_group">
				<table class="table table-striped" id="doug-neiner-five" style="width:920px;" >	
					<thead>
					<tr>
						<th width="70px"><a ng-click="sort_by('$index')"><button class="sort_tool">No.<span class="caret"></span></button></a></th>
						<th width="170px"><a ng-click="sort_by('historyID')"><button class="sort_tool">Product Name<span class="caret"></span></button></a></th>
						<th width="170px"><a ng-click="sort_by('name')"><button class="sort_tool">Category<span class="caret"></span></button></a></th>
						<th width="170px"><a ng-click="sort_by('email')"><button class="sort_tool">Publisher<span class="caret"></span></button></a></th>
						<th width="170px"><a ng-click="sort_by('first_download_date')"><button class="sort_tool">Group<span class="caret"></span></button></a></th>
						<th width="170px"><a ng-click="sort_by('first_download_date')"><button class="sort_tool">Release<span class="caret"></span></button></a></th>											
					</tr>
					</thead>				
					<tbody>
						<tr ng-if="productData.length <= 0">
							<td colspan="6" align="center">
								<span class="glyphicon glyphicon-exclamation-sign"></span> &nbsp;<strong>No Product Found...</strong>
							</td>
						</tr>
						<tr ng-repeat="data in productData">
							<td width="70px" align="center">{{ $index+1 }}</td>
							<td width="170px">{{data.name}}</td>
							<td width="170px">{{data.category}}</td>
							<td width="170px">{{data.author}} </td>
							<td width="170px">{{data.group}}</td>
							<td width="170px">{{data.release_date | asDate | date:'dd MMM yyyy'}}</td>
						</tr>
					</tbody>
				</table>
				</div>
			</div>
		</div>
	</div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->