<!-- Mail Box -->
<div class="modal fade" id="replyFeedback">
<!-- Hidden Slime Customer Service -->

  <div class="modal-dialog">
    <div class="modal-content">
		<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h3>&nbsp;<span class="glyphicon glyphicon-envelope"></span>&nbsp; Reply Mail</h3>
		</div>
		
		<div class ="modal-body" >
		<div class="form-horizontal">
			<div class="send_group">
			
			<div class="alert alert-danger alert-dismissible d_none" role="alert" id="errorMail">
			  <!-- <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button> -->
			  <strong>Error!</strong> &nbsp;<span id="errorMailText"></span>
			</div>
			
			
				<div class="form-group">
					<label class="col-md-3 control-label">Sender</label>
					<div class="col-md-9">
						<label class="control-label"  id="feedback_sender"></label>
					</div>
				
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Date reply</label>
					<div class="col-md-9"  >
						<label class="control-label"  id="feedback_date"></label>	
					</div>
				
				</div>
				</div>
				
				<div class="form-group">
				<label class="col-md-3 control-label">Message</label>
				<div class="col-md-9" >
					<label class="control-label"  id="feedback_msg"></label>	
				</div>
				</div>		
			
			</div>
		</div>
		<div class="modal-footer">
			<div class="progress d_none" id="progressbar">
			  <div class="progress-bar progress-bar-striped active w-100"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100">
				<span class="sr-only">Loading...</span>
			  </div>
			</div>
		</div>
		</div>
	</div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->