<!-- Mail Box -->
<div class="modal fade" id="mailFeedback">
<!-- Hidden Slime Customer Service -->
<input type="hidden" id="hid_feedback_email" name="hid_feedback_email" />
<input type="hidden" id="hid_feedback_subject" name="hid_feedback_subject" />
<input type="hidden" id="hid_feedback_review" name="hid_feedback_review" />
<input type="hidden" id="hid_feedback_name" name="hid_feedback_name" />
<input type="hidden" id="hid_feedback_feedbackid" name="hid_feedback_feedbackid" />
<input type="hidden" id="hid_feedback_projectid" name="hid_feedback_projectid" />
  <div class="modal-dialog">
    <div class="modal-content">
		<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h3>&nbsp;<span class="glyphicon glyphicon-new-window"></span>&nbsp; Reply Feedback</h3>
		</div>
		
		<div class ="modal-body" >
		<div class="form-horizontal">
			<div class="send_group">
			
			<div class="alert alert-danger alert-dismissible d_none" role="alert" id="errorMail">
			  <!-- <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button> -->
			  <strong>Error!</strong> &nbsp;<span id="errorMailText"></span>
			</div>
			
			<form>
				<div class="form-group">
				<label class="col-md-2 control-label">To</label>
				<div class="col-md-10">
					<input type="text" class="form-control" name="receiver" placeholder="Receiver" id="receiver" disabled />
				</div>
				
				</div>

				</div>
				
				<div class="form-group">
				<label class="col-md-2 control-label">Message</label>
				<div class="col-md-10">
				<textarea class="form-control msgbox" name="message" style="resize:none" placeholder="Input message" id="message_email"></textarea>
				</div>
				</div>		
			</form>	
			</div>
		</div>
		<div class="modal-footer">
			<div class="progress d_none" id="progressbar">
			  <div class="progress-bar progress-bar-striped active w-100"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100">
				<span class="sr-only">Loading...</span>
			  </div>
			</div>
			<button type="button" id="btsendreply" class="btn btn-primary pull-right" ng-click="sendReply($event)"><i class="glyphicon glyphicon-share-alt"></i> &nbsp;Send</button>
		</div>
		</div>
	</div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->