<?php echo $this->doctype();?>
<html ng-app="server_claim_log">
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>
<body class="bd_sgift bd_claim_log" ng-controller="claim_logCrtl">

	<?php echo $this->render("includes/header.phtml"); ?>
	<?php echo $this->render("includes/hidden.phtml"); ?>
	<div class="ch-container">
	<div class="row">
	   
	<!-- left menu starts -->
	<?php echo $this->render("includes/menu.phtml"); ?>
			
	<div id="content" class="col-lg-12 col-sm-12 push">
		<?php
			$crumb = array("Home" => $this->baseUrl,
					"Server Log" => "active",
					"Claim Log" => "active");
			$array = array(
					"item" => $crumb,
					"class" => "col-lg-7",
					"style" => "padding-right:0px"
					);
			echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
		?>
		
		<div class="col-lg-5" id="search-crumb" style="padding-left:0px;">
			<div class="col-lg-8 pull-right" id="search_container" style="padding-right:0px; padding-left:5px;">
				<form action="<?php echo $this->baseUrl;?>/serverlog/claimlog" method="GET" role="form" id="search-form">
					<div class="input-group">
					<span class="input-group-btn">
						<button class="btn btn-default search-btn" type="button" id="advanced_search_button"><span class="caret"></span></button>
					</span>
					<input type="text" class="form-control" placeholder="Search.." name="q" id="input_search" value="<?php echo $this->param->q;?>">
					<span class="input-group-btn">
						<button class="btn btn-default" type="submit" ><span class="glyphicon glyphicon-search"></span></button>
					</span>
					</div><!-- /input-group -->
				</form>
			</div><!-- /.col-lg-4 col-lg-push-4-->
			
			<div class="btn-group pull-right" id="export_csv">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
					<span class="glyphicon glyphicon-folder-open"></span> &nbsp; Export CSV &nbsp;&nbsp;<span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu" role="menu">
					<li><a ng-click="exportCurrent($event)" href="#">Export Filtered Data</a></li>
					<li><a ng-click="exportTop1000($event)" href="#">Export Top 1000</a></li>
				  </ul>
			</div>
		</div>
		
		<div class="col-lg-6">
			<div class="advanced_search_container col-sm-10" id="advanced_search_container">
				<div class="panel panel-default">
					<div class ="panel-body" >
						<h3>Advance Search</h3><hr/>
						<form action="<?php echo $this->baseUrl;?>/serverlog/claimlog" method="GET" role="form" class="form-horizontal" id="advance-search-form">
							<div class="form-horizontal">
								<div class="advanced-input-group">
									<div class="form-group">
										<label for="inputEmail3" class="col-sm-3 control-label">Email</label>
										<div class="col-sm-9">
										  <input type="text" class="form-control advanced-input" placeholder="Email" name="email" id="email" value="<?php echo $this->param->email;?>">
										</div>
									 </div>
									 <div class="form-group">
										<label for="inputEmail3" class="col-sm-3 control-label">IMEI / MAC Address</label>
										<div class="col-sm-9">
											<input type="text" class="form-control advanced-input" placeholder="IMEI / MAC Address" name="imei_or_mac" id="imei_or_mac" value="<?php echo $this->param->imei_or_mac;?>">
										</div>
									 </div>
									 
									 <div class="form-group">
										<label for="inputEmail3" class="col-sm-3 control-label">Device</label>
										<div class="col-sm-9">
											<input type="text" class="form-control advanced-input" placeholder="Device" name="model" id="model" value="<?php echo $this->param->model;?>">
										</div>
									 </div>
									 
									 <div class="form-group">
										<label for="inputEmail3" class="col-sm-3 control-label">Merchant</label>
										<div class="col-sm-9">
											<input type="text" class="form-control advanced-input" placeholder="Merchant" name="merchant" id="merchant" value="<?php echo $this->param->merchant;?>">
										</div>
									 </div>
									 
									 <div class="form-group">
										<label for="inputEmail3" class="col-sm-3 control-label">Coupon Title</label>
										<div class="col-sm-9">
											<input type="text" class="form-control advanced-input" placeholder="Coupon Title" name="promo_name" id="promo_name" value="<?php echo $this->param->promo_name;?>">
										</div>
									 </div>
									 
									 <div class="form-group">
										<label for="inputEmail3" class="col-sm-3 control-label">Voucher ID</label>
										<div class="col-sm-9">
											<input type="text" class="form-control advanced-input" placeholder="Voucher ID" name="redeem_code" id="redeem_code" value="<?php echo $this->param->redeem_code;?>">
										</div>
									 </div>
									 
									 <div class="form-group">
										<label for="inputEmail3" class="col-sm-3 control-label">Status</label>
										<div class="col-sm-9">
											<input type="text" class="form-control advanced-input" placeholder="Status" name="status" id="status" value="<?php echo $this->param->status;?>">
										</div>
									 </div>
									 
									 <div class="form-group">
										<label for="inputEmail3" class="col-sm-3 control-label">Status Code</label>
										<div class="col-sm-9">
											<select name="status_code" id="status_code" class="form-control">
												<option value="" >All Status</option>
												<option value="200" <?php echo ($this->param->status_code == 200) ? 'selected' : ''; ?> >Success</option>
												<option value="201" <?php echo ($this->param->status_code == 201) ? 'selected' : ''; ?> >Created</option>
												<option value="202" <?php echo ($this->param->status_code == 202) ? 'selected' : ''; ?> >Accepted</option>
												<option value="204" <?php echo ($this->param->status_code == 204) ? 'selected' : ''; ?> >No Content</option>
												<option value="400" <?php echo ($this->param->status_code == 400) ? 'selected' : ''; ?>>Bad Request</option>
												<option value="403" <?php echo ($this->param->status_code == 403) ? 'selected' : ''; ?>>Forbidden</option>
												<option value="404" <?php echo ($this->param->status_code == 404) ? 'selected' : ''; ?>>Not Found</option>
												<option value="413" <?php echo ($this->param->status_code == 413) ? 'selected' : ''; ?>>Request Entity Too Large</option>
												<option value="500" <?php echo ($this->param->status_code == 500) ? 'selected' : ''; ?>>Internal Server Error</option>
												<option value="503" <?php echo ($this->param->status_code == 503) ? 'selected' : ''; ?>>Service Unavailable</option>
											</select>
										</div>
									 </div>
									 
									 <div class="form-group">
										<label for="inputEmail3" class="col-sm-3 control-label">Claim At</label>
										<div class="col-sm-9">
											<input type="text" class="form-control inline date"  name="start_claim" id="start_claim" value="<?php echo $this->param->start_claim; ?>" placeholder="YYYY-MM-DD" style="width:48%" /> 
											-
											<input type="text" class="form-control inline date" style="width:48%" name="end_claim" value="<?php echo $this->param->end_claim; ?>" placeholder="YYYY-MM-DD" id="end_claim" />
										</div>
									 </div>
									<button class="btn btn-primary search-btn pull-right" id="adv-button"><span class="glyphicon glyphicon-search"></span> &nbsp;Search</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-sm-12">
			<div class="panel panel-default">
				<div class="panel-body">					
					<div class="row">
						
						<div class="form-group pull-left form-inline" style="margin-left:15px;">
							<form class="form-inline" role="form">
							<span class="pull-left lbl"><h5>&nbsp; <i class="glyphicon glyphicon-eye-open"></i> &nbsp;Showing &nbsp;<strong>{{search_list.length | number:0}}</strong>&nbsp; from 
									&nbsp;<strong>{{totalData | number:0}}</strong>&nbsp; data</h5></span>
							</form>
						</div>
			
						<div class="form-group pull-right form-inline" style="margin-right:15px;">
							<div class="form-group">
								<div class="input-group ">
									<div class="input-group-addon">
										<span class="glyphicon glyphicon-filter"></span>&nbsp;&nbsp;<span class="badge">{{filtered.length | number:0}}</span>
									</div>
									<input class="form-control" ng-model="query[queryBy]" placeholder="Type the filter here.." >
								</div>
							</div>
							<div class="form-group">
								<select class="form-control" ng-model="queryBy">
									<option value="$">All</option>
									<option value="promo_id">Promo ID</option>
									<option value="name">Name</option>
									<option value="email">Email</option>
									<option value="model">Device</option>
									<option value="imei_or_mac">IMEI/MAC</option>
									<option value="merchant">Merchant</option>
									<option value="promo_name">Coupon Title</option>
									<option value="claim_type">Claim Type</option>
									<option value="redeem_code">Voucher Code</option>
									<option value="status">Status</option>
								</select>		
							</div>
							&nbsp;
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
									<span class="glyphicon glyphicon-time"></span>&nbsp;&nbsp;<span class="caret"></span>
								</button>
								<ul class="dropdown-menu" role="menu">
									<li><a id="btall" ng-click="start_date='';end_date='';Range = ''" value="all" href="#">All</a></li>
									<li><a id="bt7days" ng-click="start_date='';end_date='';Range = 7" value="7days" href="#">7 Days</a></li>
									<li><a id="bt30days" ng-click="start_date='';end_date='';Range = 30" value="30days" href="#">30 Days</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class='tb-test'>
						<div class="t-c">
							<table class="table table-striped" id="transaction_table">	
								<thead>
									<tr>
										<th width="220px" style="text-align:center;"><a ng-click="sort_by('promo_id')"><button class="sort_tool">Promo ID</button></a></th>
										<th width="8%" style="text-align:center;"><a ng-click="sort_by('claim_time | asDate')"><button class="sort_tool">Claim At</button></a></th>
										<th width="8%" style="text-align:center;"><a ng-click="sort_by('name')"><button class="sort_tool">Name</button></a></th>
										<th width="8%" style="text-align:center;"><a ng-click="sort_by('email')"><button class="sort_tool">Email</button></a></th>
										<th width="8%" style="text-align:center;"><a ng-click="sort_by('model')"><button class="sort_tool">Device</button></a></th>
										<th width="8%" style="text-align:center;"><a ng-click="sort_by('imei_or_mac')"><button class="sort_tool">IMEI / MAC</button></a></th>
										<th width="8%" style="text-align:center;"><a ng-click="sort_by('type')"><button class="sort_tool">Type</button></a></th>
										<th width="8%" style="text-align:center;"><a ng-click="sort_by('merchant')"><button class="sort_tool">Merchant</button></a></th>
										<th width="8%" style="text-align:center;"><a ng-click="sort_by('promo_name')"><button class="sort_tool">Coupon Title</button></a></th>
										<th width="8%" style="text-align:center;"><a ng-click="sort_by('claim_type')"><button class="sort_tool">Claim Type</button></a></th>
										<th width="8%" style="text-align:center;"><a ng-click="sort_by('redeem_code')"><button class="sort_tool">Voucher Code</button></a></th>
										<th width="8%" style="text-align:center;"><a ng-click="sort_by('status')"><button class="sort_tool">Status</button></a></th>
									</tr>
								</thead>				
								<tbody scroll>
									<tr ng-repeat="x in filtered = (search_list | filter:query | filter:queryFilter | orderBy:predicate:reverse)">
										<td width="220px" style="word-break:break-all;">{{x.promo_id}}</td>
										<td width="8%" style="text-align:center">{{x.claim_time| asDate | date:'dd MMM yyyy - HH:mm:ss'}}</td>
										<td width="8%" style="text-align:center">{{ (x.name == null) ? '-' : x.name}}</td>
										<td width="8%" style="text-align:center">{{ (x.email == null) ? '-' : x.email }}</td>
										<td width="8%" style="text-align:center">{{ (x.model == null) ? '-' : x.model}}<br/>{{ (x.product_name == null) ? '-' : x.product_name}}</td>
										<td width="8%" style="text-align:center">{{x.imei_or_mac }}</td>
										<td width="8%" style="text-align:center">{{x.type }}</td>
										<td width="8%" style="text-align:center" ng-bind-html="trustHtml( ((x.merchant == null) ? '-' : x.merchant) )"></td>
										<td width="8%" style="text-align:center" ng-bind-html="trustHtml( ((x.promo_name == null) ? '-' : x.promo_name) )"></td>
										<td width="8%" style="text-align:center">{{ (x.claim_type == null) ? '-' : x.claim_type }}</td>
										<td width="8%" style="text-align:center">{{ (x.redeem_code == null) ? '-' : x.redeem_code }}</td>
										<td width="8%" style="text-align:center">{{ (x.status == null) ? '-' : x.status}}</td>
									</tr>
								</tbody>
							</table>
						</div>
						
						<div class="bg-loading">
							<div class="loading-text">
							<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="25px" height="25px"/>  &nbsp; &nbsp; <b>Loading...</b>
							</div>
						</div>
					</div>
					<center>
					<div class="bg-log-loading" style="display:block">
						<div class="loading-text">
							<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="75px" height="75px"/><br/><h3><b>Loading...</b></h3>
						</div>
					</div>
					</center>
				</div>
			</div>
		</div>
	</div>
	<!-- Cover -->
	<div class="cover"></div>
	</body>	
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/serverlog/claim_log.js"); ?>