<div class="col-sm-12">
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
		<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
		<li data-target="#carousel-example-generic" data-slide-to="1"></li>
	  </ol>

	  <!-- Wrapper for slides -->
	  <div class="carousel-inner">
		<div class="item active">
		  <img src="<?php echo $this->baseUrl;?>/assets/images/slime2.jpg" class="img-responsive" alt="tes01" width="100%" />
		  <div class="carousel-caption">
		  </div>
		</div>
		<div class="item">
		  <img src="<?php echo $this->baseUrl;?>/assets/images/galgift.jpg" class="img-responsive" alt="tes02" width="100%"/>
		  <div class="carousel-caption">
		  </div>
		</div>
	  </div>

	  <!-- Controls -->
	  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left"></span>
	  </a>

	  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right"></span>
	  </a>
	</div>
</div>
