<!-- Download Box -->
<div class="modal fade" id="download_slime">
  <div class="modal-dialog" style="width:1335px">
    <div class="modal-content">
		<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h3><span class="glyphicon glyphicon-list-alt"></span>  &nbsp;Download History</h3>
		</div>
		
		<div class ="modal-body" >
			<div class="form-horizontal">
				<div class="send_group">
				<table class="table table-striped" style="width:1300px;" >	
					<thead>
					<tr>
						<th width="80px"><a ng-click="sort_by('historyID')"><button class="sort_tool">Date Time<span class="caret"></span></button></a></th>
						<th width="160px"><a ng-click="sort_by('name')"><button class="sort_tool">Email<span class="caret"></span></button></a></th>
						<th width="200px"><a ng-click="sort_by('email')"><button class="sort_tool">Device Model<span class="caret"></span></button></a></th>
						<th width="90px"><a ng-click="sort_by('device_model')"><button class="sort_tool">Publication<span class="caret"></span></button></a></th>
						<th width="100px"><a ng-click="sort_by('first_download_date')"><button class="sort_tool">Status<span class="caret"></span></button></a></th>
						<th width="150px"><a ng-click="sort_by('app');"><button class="sort_tool">Push to User's Devices<span class="caret"></span></button></a></th>					
					</tr>
					</thead>				
					<tbody scroll>
						<tr ng-repeat="data in download | filter:queryd | orderBy:predicated:reversed">
							<td width="185px">{{data.download_time | asDate | date:'dd MMM yyyy - HH:mm'}}</td>
							<td width="18%">{{data.email}}</td>
							<td width="18%">{{data.device_model}} <br/><em>{{(data.product_name == null) ? '- UNKNOWN -' : data.product_name}} </em><br/> <strong>{{data.device_identifier}}</strong></td>
							<td width="18%">{{data.pname}} <br/> <strong>{{data.author}}</strong></td>
							<td width="18%">{{data.status}}</td>
							<td width="18%" align="center"><button type='button' ng-click="pushToDevices($event, data)" class='btn btn-primary'><i class="glyphicon glyphicon-envelope"></i> &nbsp; Push to Devices</button></td>
						</tr>
					</tbody>
				</table>
				</div>
			</div>
		</div>
	</div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->