<!-- Header -->
<div class="header-atas" role="navigation"> 
	<div class="navbar-inner navbar-fixed-top push">

		<div class="fixed-menu row">
			<a class="menu-link navbar-menu navbar-left" href="#mn_publisher_package">
			<img src="<?php echo $this->baseUrl;?>/assets/images/menu-alt-512.png" style='color:white;' alt="Menu">
			</a> 

			<a class="navbar-brand navbar-left" href="<?php echo $this->baseUrl;?>">
			<img class="hidden-xs" src="<?php echo $this->baseUrl;?>/assets/img/logo20.png" alt="Samsung Logo"/>
			<span class="title" style="color: #222">Local Projects Reports</span>
			</a>
			
			<span class="title-kanan navbar-right">
			<div class="btn-group">
			<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" id="userbutton">
				<span><i class="glyphicon glyphicon-user"></i></span>
				<span class="hidden-xs">&nbsp;<strong><?php echo $this->mySession->rolename;?></strong>&nbsp;-&nbsp;<?php echo $this->mySession->username;?>&nbsp;</span> 
				<span class="caret"></span>
			</button>
			<ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dLabel">
				<li class="user hidden-md hidden-lg hidden-sm"><a href="#" ><span><b><?php echo $this->mySession->username;?></b></span></a></li>
				<li><a href="<?php echo $this->baseUrl;?>/main/changepass" ><span><i class="glyphicon glyphicon-lock"></i> &nbsp;Change Password</span></a></li>
				<li><a href="<?php echo $this->baseUrl;?>/main/signout"><i class="glyphicon glyphicon-log-out"></i> &nbsp;Sign-out</a></li>
			</ul>
			</div>
			</span>
			
			<div class='clear'></div>
		 </div>
		
    </div>
	
</div>
 <!-- Alert Dialog -->
<div class="alert alert-dismissible d_none" role="alert" id="alertDialog">
	<!--<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>-->
	<strong id="textHeader"></strong>, &nbsp;<span id="alertDialogText"></span>
</div>



<!-- Cover -->
<div class="cover"></div>