<!-- Global Settings -->
<input type="hidden" id="hid_role" name="hid_role" value="<?php echo $this->mySession->role; ?>" />

<!-- Hidden Value -->
<input type="hidden" id="hid_chart_date" name="hid_chart_date" value="<?php echo implode(",", $this->dataDate);?>" />
<input type="hidden" id="hid_chart_data" name="hid_chart_data" value="<?php echo implode(",", $this->dataDl);?>" />
<div class="d_none" id="hid_log_data" name="hid_log_data"><?php echo $this->logData;?></div>
<div class="d_none" id="hid_slime_data" name="hid_slime_data"><?php echo $this->slimeData;?></div>
<div class="d_none" id="hid_user_data" name="hid_user_data"><?php echo $this->userData;?></div>

<!-- User Hidden Value -->
<input type="hidden" id="hid_user_notif"  name="hid_user_notif" value="<?php echo $this->notif;?>" />
<input type="hidden" id="hid_user_notif_message"  name="hid_user_notif_message" value="<?php echo $this->notif_message;?>" />

<!-- Hidden Slime Favourite Download -->
<div class="d_none" id = "favourite_all" name = "favourite_all"><?php echo $this->favouriteAll; ?></div>

<!-- Hidden Slime Customer Service -->
<input type="hidden" id="hid_param_search" name="hid_param_search" value="<?php echo $this->param->search;?>" />
<input type="hidden" id="hid_param_email" name="hid_param_email" value="<?php echo $this->param->email;?>" />
<input type="hidden" id="hid_param_imei" name="hid_param_imei" value="<?php echo $this->param->imei;?>" />
<input type="hidden" id="hid_param_device" name="hid_param_device" value="<?php echo $this->param->device;?>" />
<input type="hidden" id="hid_param_trans_id" name="hid_param_trans_id" value="<?php echo $this->param->transaction_id;?>" />
<input type="hidden" id="hid_param_trans_date" name="hid_param_trans_date" value="<?php echo $this->param->transaction_date;?>" />
<input type="hidden" id="hid_param_publication" name="hid_param_publication" value="<?php echo $this->param->publication_name;?>" />
<div class="d_none" id="hid_subscription" name="hid_subscription"><?php echo $this->subscriptionOrder; ?></div>
<input type="hidden" id="hid_param_pid" name="hid_param_pid" value="<?php echo $this->param->pid; ?>" />
<input type="hidden" id="hid_param_pname" name="hid_param_pname" value="<?php echo $this->param->pname; ?>" />

<!-- Hidden Sgift Customer Service -->
<div class="d_none" id = "simpan_search" name = "simpan_search"><?php echo $this->arrs; ?></div>
<div class="d_none" id = "simpan_search_merchant" name = "simpan_search_merchant"><?php echo $this->arrs2; ?></div>
<input type="hidden" id="hid_param_q" name="hid_param_q" value="<?php echo $this->param->q;?>" />
<input type="hidden" id="hid_param_email" name="hid_param_email" value="<?php echo $this->param->email;?>" />
<input type="hidden" id="hid_param_imei" name="hid_param_imei" value="<?php echo $this->param->imei;?>" />
<input type="hidden" id="hid_param_device" name="hid_param_device" value="<?php echo $this->param->device;?>" />
<input type="hidden" id="hid_param_telp" name="hid_param_telp" value="<?php echo $this->param->telp;?>" />
<input type="hidden" id="hid_param_store" name="hid_param_store" value="<?php echo $this->param->store;?>" />
<input type="hidden" id="hid_param_voucher_id" name="hid_param_voucher_id" value="<?php echo $this->param->voucher_id;?>" />

<!-- Hidden Customer -->
<div class="d_none" id = "customer_search" name = "customer_search_sgift"><?php echo $this->arrs; ?></div>
<div class="d_none" id = "customer_users_app" name = "customer_users_app"><?php echo $this->user_mail_list; ?></div>

<!-- Hidden Confirm -->
<input type="hidden" id="hid_confirm" name="hid_confirm" value="<?php echo $this->param->ans; ?>" />
<input type="hidden" id="hid_mode" name="hid_mode" value="<?php echo $this->param->mode; ?>" />
<input type="hidden" id="hid_app" name="hid_app" value="<?php echo $this->param->app; ?>" />
<input type="hidden" id="hid_mail_id" name="hid_mail_id" value="<?php echo $this->param->id; ?>" />
<input type="hidden" id="hid_mail_newemail" name="hid_mail_newemail" value="<?php echo $this->param->newemail; ?>" />

<!-- Hidden Sgift & SLime Review -->
<div class="d_none" id="review_result" name = "review_result"><?php echo $this->arrs; ?></div>
<input type="hidden" id="hid_feedback" name="hid_feedback" value="<?php echo $this->feedback; ?>" />

<!-- Hidden Mail -->
<input type="hidden" id="hid_email" name="hid_email" />
<input type="hidden" id="hid_email_deviceid" name="hid_email_deviceid" />
<input type="hidden" id="hid_email_devicetype" name="hid_email_devicetype" />
<input type="hidden" id="hid_email_name" name="hid_email_name" />
<input type="hidden" id="hid_email_app" name="hid_email_app" />
<input type="hidden" id="hid_email_status" name="hid_email_status" />
<input type="hidden" id="hid_email_id" name="hid_email_id" />

<!-- Hidden Change Password -->
<input type="hidden" id="hid_user_flag"  name="hid_user_flag" value="<?php echo $this->is_first; ?>" />

<!-- Hidden Redeem Merchant -->
<div class="d_none" id = "simpan_search" name = "simpan_search"><?php echo $this->arrs; ?></div>
<input type="hidden" id="hid_param_q" name="hid_param_q" value="<?php echo $this->param->q;?>" />
<input type="hidden" id="hid_param_name" name="hid_param_name" value="<?php echo $this->param->user_name;?>" />
<input type="hidden" id="hid_param_device" name="hid_param_device" value="<?php echo $this->param->device;?>" />
<input type="hidden" id="hid_param_merchant" name="hid_param_merchant" value="<?php echo $this->param->merchant;?>" />
<input type="hidden" id="hid_param_store" name="hid_param_voucher" value="<?php echo $this->param->voucher;?>" />
<input type="hidden" id="hid_param_promo" name="hid_param_promo" value="<?php echo $this->param->promo;?>" />
<input type="hidden" id="hid_param_channel" name="hid_param_channel" value="<?php echo $this->param->channel;?>" />
<input type="hidden" id="hid_param_type" name="hid_param_type" value="<?php echo $this->param->type;?>" />

<!-- Hidden Promo Merchant -->
<div class="d_none" id = "hid_merchant_promo" name = "hid_merchant_promo"><?php echo $this->merchant_promo; ?></div>

<!-- Hidden Server Log -->
<div class="d_none" id = "hid_redeem_log" name = "hid_redeem_log"><?php echo $this->redeem_log; ?></div>
<div class="d_none" id = "hid_claim_log" name = "hid_claim_log"><?php echo $this->claim_log; ?></div>

<!-- Hidden Product GGI -->
<div class="d_none" id = "hid_merchant_product_amount" name = "hid_merchant_product_amount"><?php echo $this->merchant_promo_amount; ?></div>
<div class="d_none" id = "hid_merchant_product_detail" name = "hid_merchant_product_detail"><?php echo $this->merchant_promo_detail; ?></div>

<!-- Hidden Monthly Revenue -->
<div class="d_none" id = "hid_monthly_revenue" name = "hid_monthly_revenue"><?php echo $this->monthPie; ?></div>
<div class="d_none" id = "hid_monthly_download" name = "hid_monthly_download"><?php echo $this->downloadPie; ?></div>
<div class="d_none" id = "hid_monthly_graph" name = "hid_monthly_graph"><?php echo $this->monthlyGraph; ?></div>

<!-- Hidden Publisher Dashboard -->
<div class="d_none" id = "hid_publication_revenue" name = "hid_publication_revenue"><?php echo $this->monthRevenue; ?></div>
<div class="d_none" id = "hid_device_contribution" name = "hid_device_contribution"><?php echo $this->devContribution; ?></div>
<div class="d_none" id = "hid_download_month" name = "hid_download_month"><?php echo $this->downloadMonth; ?></div>

<!-- Hidden Publisher Dashboard -->
<input type="hidden" id="hid_category_id" name="hid_category_id" value="<?php echo $this->param->cat;?>" />

<!-- Hidden Userbase Dashboard -->
<div class="d_none" id="activeMonthly"><?php echo $this->activeMonthlyTemp; ?></div>
<div class="d_none" id="activeWeekly"><?php echo $this->activeWeeklyTemp; ?></div>
<div class="d_none" id="activeDaily"><?php echo $this->activeDailyTemp; ?></div>
<div class="d_none" id="allDeviceSegment"><?php echo $this->allDeviceSegment; ?></div>