<!-- Mail Box -->
<div class="modal fade" id="mailChooser">
  <div class="modal-dialog">
    <div class="modal-content">
		<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h3>&nbsp;<span class="glyphicon glyphicon-new-window"></span>&nbsp; Request Admin</h3>
		</div>
		
		<div class ="modal-body" >
		<div class="form-horizontal">
			<div class="send_group">
			
			<div class="alert alert-danger alert-dismissible d_none" role="alert" id="errorMail">
			  <!-- <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button> -->
			  <strong>Error!</strong> &nbsp;<span id="errorMailText"></span>
			</div>
			
			<form>
				<div class="form-group">
				<label class="col-md-2 control-label">To</label>
				<div class="col-md-10">
					<select data-placeholder="Receiver" id="cbto" multiple class="chosen-select" name="receiver">
						<!-- Destination Email -->
					</select>
				</div>
				
				</div>

				<div class="form-group">
				<label class="col-md-2 control-label">Subject</label>
				<div class="col-md-10">
				<input type="text" class="form-control" name="subject" placeholder="Subject" id="subject_email" disabled />
				</div>
				</div>
				
				<div class="form-group">
				<label class="col-md-2 control-label">Reason</label>
				<div class="col-md-10">
				<textarea class="form-control msgbox" name="message" style="resize:none" placeholder="Your reason here.." id="reason_email"></textarea>
				</div>
				</div>		
			</form>	
			</div>
		</div>
		<div class="modal-footer">
			<div class="progress d_none" id="progressbar">
			  <div class="progress-bar progress-bar-striped active w-100"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100">
				<span class="sr-only">Loading...</span>
			  </div>
			</div>
			<button type="button" id="btsendmail" class="btn btn-primary pull-right" ><i class="glyphicon glyphicon-share-alt"></i> &nbsp;Send Request</button>
		</div>
		</div>
	</div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->