<?php

echo $this->headLink()->prependStylesheet($this->baseUrl."/assets/bootstrap/css/bootstrap.min.css")
					  ->prependStylesheet($this->baseUrl."/assets/bootstrap/css/bootstrap-cerulean.min.css")
					  ->prependStylesheet($this->baseUrl."/assets/bootstrap/css/bootstrap-theme.min.css")
					  ->prependStylesheet($this->baseUrl."/assets/chosen_v1.1.0/chosen.min.css")
					  ->prependStylesheet($this->baseUrl."/assets/jquery/jquery-ui.min.css")
					  ->prependStylesheet($this->baseUrl."/assets/font-awesome/css/font-awesome.min.css")
					  ->prependStylesheet($this->baseUrl."/css/style.css")
					  ->prependStylesheet($this->baseUrl."/css/responsive.css")
					  ->headLink(array('rel' => 'shortcut icon','href'=> $this->baseUrl."/favicon/favicon.png", 'PREPEND'));
				 

echo $this->headScript()->appendFile($this->baseUrl."/assets/jquery/jquery-1.11.1.min.js")
						->appendFile($this->baseUrl."/js/global.js")
						->appendFile($this->baseUrl."/js/bigSlide.js")
						->appendFile($this->baseUrl."/assets/bootstrap/js/bootstrap.min.js")
						->appendFile($this->baseUrl."/assets/jquery/Chart.js")
						->appendFile($this->baseUrl."/assets/jquery/highstock/highstock.js")
						->appendFile($this->baseUrl."/assets/jquery/highcharts.js")
						->appendFile($this->baseUrl."/assets/jquery/modules/exporting.js")
						->appendFile($this->baseUrl."/assets/jquery/jquery-ui.min.js")
						->appendFile($this->baseUrl."/assets/jquery/angular.min.js")
						->appendFile($this->baseUrl."/assets/jquery/angular-sanitize.min.js")
						->appendFile($this->baseUrl."/assets/chosen_v1.1.0/chosen.jquery.js")
						->appendFile($this->baseUrl."/assets/jquery/css3-mediaqueries.js")
						->appendFile($this->baseUrl."/assets/jquery/modernizr.custom.52245.js")
						->appendFile($this->baseUrl."/assets/jquery/respond.js")
						->appendFile($this->baseUrl."/assets/jquery/html5.js");
						
?>
<script type="text/javascript">
	var base_url = "<?php echo $this->baseUrl;?>";
</script>