<!-- USER NOTE -->
<div class="bs-callout bs-callout-info">
	<p id="sa"><b>Super Administrator can access all menu, manage users, server logs and suspend or activate the customers.</b></p>
	<p id="ad"><b>Administrator can access all menu except manage users, server logs, and suspend or activate the customers.</b></p>
	<p id="cs"><b>Customer Service can access customers, transactions, promo, and send admin a request to suspend or activate the customers.</b></p>
	<p id="me"><b>Merchant only access merchant menu.</b></p>
	<p id="ma"><b>Merchant Aggregator only access merchant menu.</b></p>
	<p id="po"><b>Product Owner can access reports, customers, transactions, promo, and merchant menu.</b></p>
	<p id="pm"><b>Product Marketing can access customers, transactions, promo, and merchant menu.</b></p>
	<p id="sr"><b>SRIN Administrator can only access and manage Manage Samsung Apps menu.</b></p>
	<p id="pu"><b>Publisher only can access functionality that related to his publisher and publication data.</b></p>
	<p id="cspm"><b>Content &amp; services product manager (C&amp;S PM) can access functionality that related to S Lime content and services.</b></p>
</div>