<?php echo $this->doctype();?>
<html ng-app="myAppSgift">
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>
<body class="bd_g_sgift bd_cs_sgift" ng-controller="searchCrtl">
	<?php echo $this->render("includes/header.phtml"); ?>
	<?php echo $this->render("includes/hidden.phtml"); ?>
	<div class="ch-container">
	<div class="row">
	   
	<!-- left menu starts -->
	<?php echo $this->render("includes/menu.phtml"); ?>
			
	<div id="content" class="col-lg-12 col-sm-12 push">
		<?php
			$crumb = array("Home" => $this->baseUrl,
							"Customer Service" => "active",
							"Galaxy Gift ID" => "active");
			$array = array(
							"item" => $crumb,
							"class" => "col-lg-7",
							"style" => "padding-right:0px"
							);
			echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
		?>
		
		<div class="col-lg-5" id="search-crumb" style="padding-left:0px;">
			<div class="col-lg-8 pull-right" id="search_container" style="padding-right:0px; padding-left:5px;">
				<form action="<?php echo $this->baseUrl;?>/cssgift/index" method="GET" role="form" id="search-form">
					<div class="input-group">
					<span class="input-group-btn">
						<button type="button" class="btn btn-default search-btn" type="button" id="advanced_search_button">
						<span class="caret"></span><span class="sr-only">Toggle Dropdown</span>
						</button>
					</span>
					<input type="text" class="form-control" placeholder="Search.." name="q" id="input_search" value="<?php echo $this->param->q;?>">
					<span class="input-group-btn">
						<button class="btn btn-default" type="submit" ><span class="glyphicon glyphicon-search"></span></button>
					</span>
					</div><!-- /input-group -->
				</form>
			</div><!-- /.col-lg-4 col-lg-push-4-->
			
			<div class="btn-group pull-right cs-not-show" id="export_csv">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
				<span class="glyphicon glyphicon-folder-open"></span> &nbsp; Export CSV &nbsp;&nbsp;<span class="caret"></span>
				</button>
				<ul class="dropdown-menu" role="menu">
					<li><a ng-click="exportCurrent($event)" href="#">Export Filtered Document</a></li>
					<li><a ng-click="exportAll($event)" href="#">Export All Document</a></li>
				</ul>
			</div>
		</div>
		
		<div class="col-sm-6" ><div class="advanced_search_container col-sm-8" id="advanced_search_container"><div class="panel panel-default">  
			<div class ="panel-body">
			<h3>Advanced Search</h3><hr/>
				<form action="<?php echo $this->baseUrl;?>/cssgift/index" method="GET" role="form" class="form-horizontal" id="advance-search-form">
					<div class="form-horizontal"><div class="advanced-input-group">
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Email</label>
							<div class="col-sm-9">
							<input type="text" class="form-control advanced-input" placeholder="Email" name="email" value="<?php echo $this->param->email;?>">
							</div>
						</div>
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">IMEI or MAC</label>
							<div class="col-sm-9">
							<input type="text" class="form-control advanced-input" placeholder="IMEI or MAC" name="imei" value="<?php echo $this->param->imei;?>">
							</div>
						</div>
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Device</label>
							<div class="col-sm-9">
							<input type="text" class="form-control advanced-input" placeholder="Device Model" name="device" value="<?php echo $this->param->device;?>">
							</div>
						</div>
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Telephone</label>
							<div class="col-sm-9">
							<input type="text" class="form-control advanced-input" placeholder="Telephone Number" name="telp" value="<?php echo $this->param->telp;?>">
							</div>
						</div>
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Merchant</label>
							<div class="col-sm-9">
							<input type="text" class="form-control advanced-input" placeholder="Merchant Name" name="store" value="<?php echo $this->param->store;?>">
							</div>
						</div>
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Voucher ID</label>
							<div class="col-sm-9">
							<input type="text" class="form-control advanced-input" placeholder="Voucher Id" name="voucher_id" value="<?php echo $this->param->voucher_id;?>">
							</div>
						</div>
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Claim Date</label>
							<div class="col-sm-9">
								<input type="text" class="form-control inline date"  name="start_claim" id="start_claim" value="<?php echo $this->param->start_claim; ?>" placeholder="YYYY-MM-DD" style="width:48%" /> 
								-
								<input type="text" class="form-control inline date" style="width:48%" name="end_claim" value="<?php echo $this->param->end_claim; ?>" placeholder="YYYY-MM-DD" id="end_claim" />
							</div>
						 </div>
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Redeem Date</label>
							<div class="col-sm-9">
								<input type="text" class="form-control inline date"  name="start_redeem" id="start_redeem" value="<?php echo $this->param->start_redeem; ?>" placeholder="YYYY-MM-DD" style="width:48%" /> 
								-
								<input type="text" class="form-control inline date" style="width:48%" name="end_redeem" value="<?php echo $this->param->end_redeem; ?>" placeholder="YYYY-MM-DD" id="end_redeem" />
							</div>
						 </div>
						<button class="btn btn-primary search-btn pull-right" id="adv-button"><i class="glyphicon glyphicon-search"></i> &nbsp;Search</button>
					</div></div>
				</form>
			</div>
		</div></div></div>
		
		<div class="col-sm-12">
			<div class="panel panel-default">
			<div class="panel-body" style="padding-bottom:0px;">
					
			<div class="row">
			
			
			<!-- Popup -->
			<div class="panel panel-primary promo_detail_container">
			  <div class="panel-heading">
			  <button type="button" class="close white" data-dismiss="modal" id="close_promo"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h3 class="panel-title">Promo Detail</h3>
			  </div>
			  <div class="panel-body" id="detail_promo">
				Panel content
			  </div>
				<table class="table table-bordered promo_table table-striped"  >
					<thead>
						<tr>
							<th>Total Coupon</th>
							<th>Total Redeem</th>
							<th>Remaining Redeem</th>
							<th>Total Claim</th>
							<th>Remaining Claim</th>
						</tr>
					</thead>
					<tbody id="promo_number">
						<tr>
						</tr>
					</tbody>
				  </table>
			</div>
			
			<div class="panel panel-primary user_detail_container">
				<div class="panel-heading">
					<button type="button" class="close" data-dismiss="modal" id="close_user"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h3 class="panel-title">User Details</h3>
				</div>
				<div class="panel-body" id="detail_user">
					Panel content
				</div>
			</div>
			
			<!-- -->
			
			<div class="form-group pull-left form-inline" style="margin-left:15px;">
				<form class="form-inline" role="form">
				<span class="pull-left lbl"><h5>&nbsp; <i class="glyphicon glyphicon-eye-open"></i> &nbsp;Showing &nbsp;<strong>{{search_list.length | number:0}}</strong>&nbsp; from 
				&nbsp;<strong>{{totalData | number:0}}</strong>&nbsp; data</h5></span>
				</form>
			</div>
			
			<div class="form-group pull-right form-inline" style="margin-right:15px;" id="filter-textbox">
				
				<div class="form-group ">
					<div class="input-group ">
					  <div class="input-group-addon">
						<span class="glyphicon glyphicon-filter"></span>&nbsp;&nbsp;<span class="badge">{{filtered.length}}</span>
					  </div>
					  <input class="form-control" ng-model="query[queryBy]" placeholder="Type the filter here.." >
					</div>
				</div>
				
				<div class="form-group" id="filter-option">
					<select class="form-control" ng-model="queryBy" >
						<option value="$">All</option>
						<option value="voucher_id">Promo ID</option>
						<option value="email_user">Email</option>
						<option value="telp">Telephone</option>
						<option value="merchant_name">Merchant</option>
						<option value="imei">IMEI or MAC</option>
						<option value="device_model">Device</option>
					</select>		
				</div>
				
				&nbsp; &nbsp;&nbsp;
				
				<div class="btn-group">
					<div class="btn-group">
						<button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" id="time_filter">
							<span class="glyphicon glyphicon-time"></span>&nbsp;&nbsp;<span class="caret"></span>
						</button>
						<ul class="dropdown-menu" role="menu">
							<li><a id="btall" ng-click="start_date = ''; end_date = ''; DateRange = ''" value="all" href="#">All</a></li>
							<li><a id="bt7days" ng-click="start_date = ''; end_date = ''; DateRange = 7" value="7days" href="#">7 Days</a></li>
							<li><a id="bt30days" ng-click="start_date = ''; end_date = ''; DateRange = 30" value="30days" href="#">30 Days</a></li>
						</ul>
					</div>
					
					<div class="btn-group">							
					<!--date -->
					</div>
					<div class="form-group has-success" id="redeem/claim">
						<select class="form-control" ng-model="dateBy" id="redeem" style="border-radius: 0px 4px 4px 0px;">
							<option value="redeem_time" selected="selected">Redeem Time</option>
							<option value="claim_time">Claim Time</option>
						</select>
						
					</div>
				</div>
			</div>
			<div class="clear"></div>
	
			<div class='tb-test'>
			<div class="t-c">
				<table class="table table-striped" id="transaction_table" >	
					<thead>
					<tr>
						<th width="15%"><a ng-click="sort_by('promo_id')"><button class="sort_tool">Promo ID &amp; Name</button></a></th>
						<th width="12%"><a ng-click="sort_by('email_user')"><button class="sort_tool">Email</button></a></th>
						<th width="9%"><a ng-click="sort_by('telp')"><button class="sort_tool">Telephone</button></a></th>
						<th width="9%"><a ng-click="sort_by('merchant_name')"><button class="sort_tool">Merchant</button></a></th>
						<th width="14%"><a ng-click="sort_by('start_time | asDate');"><button class="sort_tool">Start-End Date</button></a></th>
						<th width="10%"><a ng-click="sort_by('imei');"><button class="sort_tool">IMEI &amp; Device</button></a></th>
						<th width="10%"><a ng-click="sort_by('redeem_time | asDate');"><button class="sort_tool">Redeem</button></a></th>
						<th width="10%"><a ng-click="sort_by('claim_time | asDate');"><button class="sort_tool">Claim</button></a></th>
						<th width="7%"><a ng-click="sort_by('voucher_id');"><button class="sort_tool">Voucher ID</button></a></th>
						<th width="5%"><a><button class="sort_tool">Push Promo</button></a></th>
						<th width="1%"></th>
						
					</tr>
					</thead>				
					<tbody scroll>
						<tr ng-repeat="x in filtered = ( search_list | filter:query | filter:queryByDay | filter:queryByPickerDay ) | orderBy:predicate:reverse ">
							<td width="15%"><a providerdata="{{x.provider_id}}" channeldata="{{x.channel_id}}" promodata="{{x.promo_id}}" batchdata="{{x.batch_id}}" campaigndata="{{x.campaign_id}}" tes-popup href="#" data-toggle="modal" data-target=".bs-example-modal-lg" test="{{ $index +1 }}" class="promo_button">{{ x.promo_id }} <br/> <span ng-bind-html="trustHtml(x.promo_name)"></span></td>
							<td width="12%"><a href="#" userdata="{{x.user_id}} " popup-user data-toggle="modal" data-target=".bs-example-modal-lg" index="{{ $index }}" class="user_button">{{ x.email_user }}</a></td>
							<td width="9%">{{ (x.telp == null) ? '-' : x.telp }}</td>
							<td width="9%" ng-bind-html="trustHtml(x.merchant_name)"></td>
							<td width="14%">{{ x.start_time | asDate | date:'dd MMM yyyy - HH:mm'}} <br/> {{ x.end_time | asDate | date:'dd MMM yyyy - HH:mm'}} </td>
							<td width="10%"><capital>{{ x.manufactur +" "+ x.device_model}}</capital><br/><em>{{ (x.product_name== null) ? '- UNKNOWN -' : x.product_name}} </em><br/><strong>{{ x.imei }}</strong></td>
							<td width="10%">{{ x.redeem_time | asDate | date:'dd MMM yyyy - HH:mm'}}</td>
							<td width="10%"><a tes-hover data-trigger='hover' class='hover_table' id='popup-ct' data='{{ $index + 1 }}'>{{ (x.claim_time==null)?'-': (x.claim_time | asDate | date:'dd MMM yyyy - HH:mm')}}</td>
							<td width="7%">{{ x.voucher_id }}</td>
							<td width="5%" align="center">
								<!-- <a href="<?php echo $this->baseUrl;?>/user/edit?id=<?php echo $temp_data[$i]['userID']; ?>">
									<button type="button" class="btn btn-primary">
									<span class="action-text">Push</span>
									</button>
								</a> -->
								-
							</td>
						</tr>
					</tbody>
				</table>
			</div>
					
			<div class="bg-loading">
				<div class="loading-text">
					<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="25px" height="25px"/>  &nbsp; &nbsp; <b>Loading...</b>
				</div>
			</div>	
			</div>
			<center>
			<div class="bg-log-loading" style="display:block;">
				<div class="loading-text">
					<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="75px" height="75px"/><br/><h3><b>Loading...</b></h3>
				</div>
			</div>
			</center>
			</div>
		</div>
		</div>
	</div>
	<!-- Cover -->
	<div class="cover"></div>
	</body>	
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/cs/sgift_search.js"); ?>