<?php echo $this->doctype();?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?php echo $this->headTitle();?>
		<?php echo $this->render("includes/script.phtml"); ?>
	</head>
	<body class="bd_managesapps">
		<?php echo $this->render("includes/header.phtml"); ?>
		<?php echo $this->render("includes/hidden.phtml"); ?>
		<div class="ch-container">
		<div class="row">
		<!-- left menu starts -->
		<?php echo $this->render("includes/menu.phtml"); ?>
		<div id="content" class="col-lg-12 col-sm-12 push">
			<?php
				$crumb = array("Home" => $this->baseUrl,							   "Management" => "active",
							   "Manage Samsung Apps" => $this->baseUrl."/managesamsung",
							   "Insert Data" => "active");
				$array = array(
								"item" => $crumb,
								"class" => "col-lg-12",
								"style" => "padding-right:15px"
							  );
				echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
			?>
			<div class="col-lg-12">
				<div class="panel panel-default"><div class="panel-body">
					<?php 
						$attr = array( "method" => "POST", 
									   "action" => $this->baseUrl."/managesamsung/insert",
									   "class" => "form-horizontal",
									   "autocomplete" => "off"
									 );
						echo $this->form("frminsert",$attr);
					?>
					<h3>&nbsp;<i class="glyphicon glyphicon-hdd"></i> &nbsp;Insert Install</h3><hr/>
					<div class="form-group">
						<label for="project_name" class="col-sm-2 control-label">Project Name</label>
						<div class="col-sm-10">
							<select class="form-control" name="project_name">								<option value="">Select Project.. </option>
								<option value="slime" <?php if($this->param->project_name=='slime')echo 'selected' ;?>>S Lime</option>								<option value="sgift" <?php if($this->param->project_name=='sgift')echo 'selected' ;?>>GALAXY Gift ID</option>								<option value="salaam" <?php if($this->param->project_name=='salaam')echo 'selected' ;?> >Salaam</option>								<option value="sfit" <?php if($this->param->project_name=='sfit')echo 'selected' ;?>>S Fit</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="install_date" class="col-sm-2 control-label">Date</label>
						<div class="col-sm-10">
							<input class="form-control" value="<?php echo $this->param->install_date;?>" type="text" id="date_text" name="install_date" data-toggle="dropdown"/>
						</div>
					</div>
					<div class="form-group" id="div_daily_install">
						<label for="daily_install" class="col-sm-2 control-label">Total Install</label>
						<div class="col-sm-10">
							<input type="text" class="form-control num" value="<?php echo $this->param->daily_install;?>" name="daily_install" id="daily_install" placeholder="Only Number" maxlength="30" />
						</div>
					</div>
					<div class="col-sm-10 col-sm-offset-2" id="div_error_daily_install" >
						<div class="form-group" id="div_daily_install">
						<label for="daily_install" style="color:red">Total install must be inserted in number only</label>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
						<button type="submit" class="btn btn-success"><span class='glyphicon glyphicon-floppy-disk'></span>&nbsp; Save</button>
						</div>
					</div>
					</form>
								</div></div>
			</div>
		</div>	
	</body>
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/managesamsung/insert.js"); ?>
