<?php echo $this->doctype();?>
<html ng-app="myAppSlime">
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>
<body class="bd_g_slime bd_slime_promo" ng-controller="searchCrtl">
<!--{{ff()}} -->
	<?php echo $this->render("includes/header.phtml"); ?>
	<?php echo $this->render("includes/hidden.phtml"); ?>
	<div class="ch-container">
	<div class="row">
	   
	<!-- left menu starts -->
	<?php echo $this->render("includes/menu.phtml"); ?>
			
	<div id="content" class="col-lg-12 col-sm-12 push">
		<?php
			$crumb = array("Home" => $this->baseUrl,
					"S Lime" => "active",
					"Promo &amp; Detail" => "active");
			$array = array(
					"item" => $crumb,
					"class" => "col-lg-7",
					"style" => "padding-right:0px"
					);
			echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
		?>
		
		<div class="col-lg-5" id="search-crumb" style="padding-left:0px;">
			<div class="col-lg-8 pull-right" id="search_container" style="padding-right:0px; padding-left:5px;">
				<form action="<?php echo $this->baseUrl;?>/promo" method="GET" role="form" id="search-form">
					<div class="input-group">
					<span class="input-group-btn">
						<button class="btn btn-default search-btn" type="button" id="advanced_search_button"><span class="caret"></span></button>
					</span>
					<input type="text" class="form-control" placeholder="Search.." name="q" id="input_search" value="<?php echo $this->param->q;?>">
					<span class="input-group-btn">
						<button class="btn btn-default" type="submit" ><span class="glyphicon glyphicon-search"></span></button>
					</span>
					</div><!-- /input-group -->
				</form>
			</div><!-- /.col-lg-4 col-lg-push-4-->
			
			<div class="btn-group pull-right" id="export_csv">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
					<span class="glyphicon glyphicon-folder-open"></span> &nbsp; Export CSV &nbsp;&nbsp;<span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu" role="menu">
					<li><a ng-click="exportCurrent($event)" href="#">Export Filtered Data</a></li>
					<li><a ng-click="exportAll($event)" href="#">Export All</a></li>
				  </ul>
			</div>
		</div>
		
		<div class="col-lg-6" >
			<div class="advanced_search_container col-sm-10" id="advanced_search_container">
			<div class="panel panel-default">
			  
			<div class ="panel-body" >
				<h3>Advance Search</h3><hr/>
				<form action="<?php echo $this->baseUrl;?>/promo" method="GET" role="form" class="form-horizontal" id="advance-search-form">
				<div class="form-horizontal">
					<div class="advanced-input-group">
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Promo Name</label>
							<div class="col-sm-9">
							  <input type="text" class="form-control advanced-input" placeholder="Promo Name.." name="promo_name" id="promo_name" value="<?php echo $this->param->promo_name;?>">
							</div>
						 </div>
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Start Date</label>
							<div class="col-sm-9">
								<input type="text" class="form-control inline date"  name="start_start_date" id="start_start_date" value="<?php echo $this->param->start_start_date; ?>" placeholder="YYYY-MM-DD" style="width:48%" /> 
								-
								<input type="text" class="form-control inline date" style="width:48%" name="end_start_date" value="<?php echo $this->param->end_start_date; ?>" placeholder="YYYY-MM-DD" id="end_start_date" />
							</div>
						 </div>
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">End Date</label>
							<div class="col-sm-9">
								<input type="text" class="form-control inline date"  name="start_end_date" id="start_end_date" value="<?php echo $this->param->start_end_date; ?>" placeholder="YYYY-MM-DD" style="width:48%" /> 
								-
								<input type="text" class="form-control inline date" style="width:48%" name="end_end_date" value="<?php echo $this->param->end_end_date; ?>" placeholder="YYYY-MM-DD" id="end_end_date" />
							</div>
						 </div>
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Valid Date</label>
							<div class="col-sm-9">
								<input type="text" class="form-control inline date"  name="start_valid_date" id="start_valid_date" value="<?php echo $this->param->start_valid_date; ?>" placeholder="YYYY-MM-DD" style="width:48%" /> 
								-
								<input type="text" class="form-control inline date" style="width:48%" name="end_valid_date" value="<?php echo $this->param->end_valid_date; ?>" placeholder="YYYY-MM-DD" id="end_valid_date" />
							</div>
						 </div>
						
						<button class="btn btn-primary search-btn pull-right" id="adv-button"><span class="glyphicon glyphicon-search"></span> &nbsp;Search</button>
					</div>
					</div>
				</form>
				</div>
				</div>
			</div>
		</div>
		
		<div class="col-sm-12">
			<div class="panel panel-default">
			
			<div class="panel-body">					
			<div class="row">
			
	
			<div class="panel panel-primary user_detail_container">
				<div class="panel-heading">
					<button type="button" class="close" data-dismiss="modal" id="close_user"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h3 class="panel-title">User Details</h3>
				</div>
				<div class="panel-body" id="detail_user">
					Panel content
				</div>
			</div>
			
			<!-- -->
			
			<div class="form-group pull-left form-inline" style="margin-left:15px;">
				<form class="form-inline" role="form">
				<span class="pull-left lbl"><h5>&nbsp; <i class="glyphicon glyphicon-eye-open"></i> &nbsp;Showing &nbsp;<strong>{{search_list.length | number:0}}</strong>&nbsp; from 
						&nbsp;<strong>{{totalData | number:0}}</strong>&nbsp; data</h5></span>
				</form>
			</div>
			
			<div class="form-group pull-right form-inline" style="margin-right:15px;">	
				
				<div class="form-group" id="filter-textbox">
					<div class="input-group ">
					  <div class="input-group-addon">
						<span class="glyphicon glyphicon-filter"></span>&nbsp;&nbsp;<span class="badge">{{filtered.length | number:0}}</span>
					  </div>
					  <input class="form-control" ng-model="query[queryBy]" placeholder="Filter by..." >
					</div>
				</div>
				<div class="form-group" id="filter-option">
					<select class="form-control" ng-model="queryBy">
						<option value="$">All</option>
						<option value="promo_name">Promo Name</option>
						<option value="start_date">Start Date</option>
						<option value="end_date">End Date</option>
						<option value="valid_date">Valid Date</option>
					</select>		
				</div>
				
				&nbsp;
				<div class="btn-group">
					<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
						<span class="glyphicon glyphicon-time"></span>&nbsp;&nbsp;<span class="caret"></span>
					</button>
					<ul class="dropdown-menu" role="menu">
						<li><a id="btall" ng-click="DateRange = ''" value="all" href="#">All</a></li>
						<li><a id="bt7days" ng-click="DateRange = 7" value="7days" href="#">7 Days</a></li>
						<li><a id="bt30days" ng-click="DateRange = 30" value="30days" href="#">30 Days</a></li>
					</ul>
				</div>
			</div>	
			</div><!-- /.row -->

			<div class='tb-test'>
				<div class="pull-left">
				</div>
				<div class="t-c">
				<?php 
					$size =  "19";
					$headSize = "450px";
				?>
				<table class="table table-striped" id="transaction_table" >	
					<thead>
					<tr>
						<th width="<?php echo $headSize; ?>"><a ng-click="sort_by('promo_name')"><button class="sort_tool">Promo Name <span class="caret"></span></button></a></th>
						<th width="<?php echo $size."%"; ?>" style="text-align:center;"><a ng-click="sort_by('start_date | asDate')"><button class="sort_tool">Start Date <span class="caret"></span></button></a></th>
						<th width="<?php echo $size."%"; ?>" style="text-align:center"><a ng-click="sort_by('end_date | asDate')"><button class="sort_tool">End Date <span class="caret"></span></button></a></th>
						<th width="<?php echo $size."%"; ?>" style="text-align:center"><a ng-click="sort_by('valid_date | asDate')"><button class="sort_tool">Valid Date <span class="caret"></span></button></a></th>						
						<th width="<?php echo $size."%"; ?>" style="text-align:center;">Detail</th>						
					</tr>
					</thead>				
					<tbody scroll>
						<tr ng-repeat="x in filtered = ( search_list | filter:query | filter:queryByDay) | orderBy:predicate:reverse ">
							<td width="<?php echo $headSize; ?>" style="word-break:break-all;">
								<span ng-bind-html="trustHtml(x.promo_name)"></span>
							</td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center">{{ (x.start_date == null) ? '-' : x.start_date | asDate | date:'dd MMM yyyy' }}</td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center">{{ (x.end_date == null) ? '-' : x.end_date | asDate | date:'dd MMM yyyy' }}</td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center">{{ (x.valid_date == null) ? '-' : x.valid_date | asDate | date:'dd MMM yyyy' }}</td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center">
								<button class="btn btn-primary" ng-click="showDevice($event, x)"><span class="glyphicon glyphicon-phone"></span></button>&nbsp;
								<button class="btn btn-warning" ng-click="showProduct($event, x)"><span class="glyphicon glyphicon-tags"></span></button>
							</td>
						</tr>
					</tbody>
				</table>
				
				</div>
					
				<div class="bg-loading">
					<div class="loading-text">
					<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="25px" height="25px"/>  &nbsp; &nbsp; <b>Loading...</b>
					</div>
				</div>	
			</div>
			<center>
			<div class="bg-log-loading" style="display:block">
				<div class="loading-text">
					<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="75px" height="75px"/><br/><h3><b>Loading...</b></h3>
				</div>
			</div>
			</center>
			</div>
		</div>
		</div>
	</div>
	<?php echo $this->render("includes/promo/devicebox.phtml");?>
	<?php echo $this->render("includes/promo/productbox.phtml");?>
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/cs/promo.js"); ?>