<?php echo $this->doctype();?>
<html ng-app="myAppSgift">
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>
<body class="bd_g_sgift bd_sgift_customer" ng-controller="searchCrtl">
	<?php echo $this->render("includes/header.phtml"); ?>
	<?php echo $this->render("includes/hidden.phtml"); ?>
	<div class="ch-container">
	<div class="row">
	   
	<!-- left menu starts -->
	<?php echo $this->render("includes/menu.phtml"); ?>
			
	<div id="content" class="col-lg-12 col-sm-12 push">
		<?php
			$crumb = array("Home" => $this->baseUrl,
							"Galaxy Gift ID" => "active",
							"Customers" => "active");
			$array = array(
					"item" => $crumb,
					"class" => "col-lg-7",
					"style" => "padding-right:0px"
					);
			echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
		?>
		
		<div class="col-lg-5" id="search-crumb" style="padding-left:0px;">
			<div class="col-lg-8 pull-right" id="search_container" style="padding-right:0px; padding-left:5px;">
				<form action="<?php echo $this->baseUrl;?>/custggi/index" method="GET" role="form" id="search-form">
					<div class="input-group">
					<span class="input-group-btn">
						<button class="btn btn-default search-btn" type="button" id="advanced_search_button"><span class="caret"></span></button>
					</span>
					<input type="text" class="form-control" placeholder="Search.." name="q" id="q" value="<?php echo $this->param->q;?>">
					<span class="input-group-btn">
						<button class="btn btn-default" type="submit" ><span class="glyphicon glyphicon-search"></span></button>
					</span>
					</div><!-- /input-group -->
				</form>
			</div><!-- /.col-lg-4 col-lg-push-4-->
			
			<div class="btn-group pull-right" id="export_csv">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
					<span class="glyphicon glyphicon-folder-open"></span> &nbsp; Export CSV &nbsp;&nbsp;<span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu" role="menu">
					<li><a ng-click="exportCurrent($event)" href="#">Export Filtered Data</a></li>
					<li><a ng-click="exportAll($event)" href="#">Export Customer By Email</a></li>
					<li><a ng-click="exportAllDevice($event)" href="#">Export Customer By Device</a></li>
				  </ul>
			</div>
		</div>
		
		<div class="col-lg-6" >
			<div class="advanced_search_container col-sm-10" id="advanced_search_container">
			<div class="panel panel-default">
			  
			<div class ="panel-body" >
				<h3>Advance Search</h3><hr/>
				<form action="<?php echo $this->baseUrl;?>/custggi/index" method="GET" role="form" class="form-horizontal" id="advance-search-form">
				<div class="form-horizontal">
					<div class="advanced-input-group panel-search">
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Name</label>
							<div class="col-sm-9">
							  <input type="text" class="form-control advanced-input" placeholder="Name.." name="name" id="name" value="<?php echo $this->param->name;?>">
							</div>
						 </div>
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Email</label>
							<div class="col-sm-9">
							  <input type="text" class="form-control advanced-input" placeholder="Email.." name="email" id="email" value="<?php echo $this->param->email;?>">
							</div>
						 </div>
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Phone</label>
							<div class="col-sm-9">
							  <input type="text" class="form-control advanced-input" placeholder="Phone.." name="phone" id="phone" value="<?php echo $this->param->phone;?>">
							</div>
						 </div>
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Gender</label>
							<div class="col-sm-9">
							<select class="form-control" name="gender" id="gender">
								<option value="">- All Gender -</option>
								<option value="male" <?php echo (strcasecmp($this->param->gender, "male") == 0) ? "selected" : ""; ?>>Male</option>
								<option value="female" <?php echo (strcasecmp($this->param->gender, "female") == 0) ? "selected" : ""; ?>>Female</option>
							</select>
							</div>
						 </div>
						
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Date of Birth</label>
							<div class="col-sm-9">
								<input type="text" class="form-control inline date"  name="start_dob" id="start_dob" value="<?php echo $this->param->start_dob; ?>" placeholder="YYYY-MM-DD" style="width:48%" /> 
								-
								<input type="text" class="form-control inline date" style="width:48%" name="end_dob" value="<?php echo $this->param->end_dob; ?>" placeholder="YYYY-MM-DD" id="end_dob" />
							</div>
						 </div>
						  <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Marital Status</label>
							<div class="col-sm-9">
							  <select class="form-control" name="marital_status" id="marital_status">
								<option value="">- All Status -</option>
								<option value="single" <?php echo (strcasecmp($this->param->marital_status, "single") == 0) ? "selected" : ""; ?>>Single</option>
								<option value="married" <?php echo (strcasecmp($this->param->marital_status, "married") == 0) ? "selected" : ""; ?>>Married</option>
							</select>
							</div>
						 </div>
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Registered Date</label>
							<div class="col-sm-9">
								<input type="text" class="form-control inline date"  name="start_registered" id="start_registered" value="<?php echo $this->param->start_registered; ?>" placeholder="YYYY-MM-DD" style="width:48%" /> 
								-
								<input type="text" class="form-control inline date" style="width:48%" name="end_registered" value="<?php echo $this->param->end_registered; ?>" placeholder="YYYY-MM-DD" id="end_registered" />
							</div>
						 </div>
						 
						  <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Address</label>
							<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" placeholder="Address.." name="address" id="address" value="<?php echo $this->param->address;?>">
							</div>
						 </div>
						
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Holiday</label>
							<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" placeholder="Holiday.." name="holiday" id="holiday" value="<?php echo $this->param->holiday;?>">
							</div>
						 </div>
						 
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Device Model</label>
							<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" placeholder="Device.." name="device_model" id="device_model" value="<?php echo $this->param->device_model;?>">
							</div>
						 </div>
						 
						 <div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">IMEI</label>
							<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" placeholder="IMEI.." name="imei" id="imei" value="<?php echo $this->param->imei;?>">
							</div>
						 </div>
						
					</div>
					<button class="btn btn-primary search-btn pull-right" id="adv-button"><span class="glyphicon glyphicon-search"></span> &nbsp;Search</button>
					</div>
				</form>
				</div>
				</div>
			</div>
		</div>
		
		<div class="col-sm-12">
			<div class="panel panel-default">
			
			<div class="panel-body">					
			<div class="row">
			
			<!-- Pop Up -->
			
			<div class="panel panel-primary user_detail_container">
				<div class="panel-heading">
					<button type="button" class="close" data-dismiss="modal" id="close_user"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h3 class="panel-title">User Details</h3>
				</div>
				<div class="panel-body" id="detail_user">
					Panel content
				</div>
			</div>
			
			<!-- -->
			
			<div class="form-group pull-left form-inline" style="margin-left:15px;">
				<form class="form-inline" role="form">
				<span class="pull-left lbl"><h5>&nbsp; <i class="glyphicon glyphicon-eye-open"></i> &nbsp;Showing &nbsp;<strong>{{search_list.length | number:0}}</strong>&nbsp; from 
						&nbsp;<strong>{{totalData | number:0}}</strong>&nbsp; data</h5></span>
				</form>
			</div>
			
			<div class="form-group pull-right form-inline" style="margin-right:15px;">	
				
				<div class="form-group" id="filter-textbox">
					<div class="input-group ">
					  <div class="input-group-addon">
						<span class="glyphicon glyphicon-filter"></span>&nbsp;&nbsp;<span class="badge">{{filtered.length | number:0}}</span>
					  </div>
					  <input class="form-control" ng-model="query[queryBy]" placeholder="Filter by..." >
					</div>
				</div>
				<div class="form-group" id="filter-option">
					<select class="form-control" ng-model="queryBy">
						<option value="$">All</option>
						<option value="name">Name</option>
						<option value="email">Email</option>
						<option value="phone_number">Phone</option>
						<option value="gender">Gender</option>
						<option value="date_of_birth">Date of Birth</option>
						<option value="marital_status">Marital Status</option>
						<option value="creation_time">Registered Date</option>
						<option value="address_province">Address</option>
						<option value="holiday">Holiday</option>
						<option value="device_model">Device</option>
					</select>		
				</div>
			</div>	
			</div><!-- /.row -->

			<div class='tb-test'>
				<div class="pull-left">
				</div>
				<div class="t-c">
				<?php 
					$size =  "10";
					$headSize = "300px";
				?>
				<table class="table table-striped" id="transaction_table" >	
					<thead>
					<tr>
						<th width="<?php echo $headSize; ?>"><a ng-click="sort_by('name')"><button class="sort_tool">Name <span class="caret"></span></button></a></th>
						<th width="<?php echo $size."%"; ?>"><a ng-click="sort_by('email')"><button class="sort_tool">Email <span class="caret"></span></button></a></th>
						<th width="<?php echo $size."%"; ?>"><a ng-click="sort_by('phone_number')"><button class="sort_tool">Phone <span class="caret"></span></button></a></th>
						<th width="<?php echo $size."%"; ?>" style="text-align:center"><a ng-click="sort_by('gender')"><button class="sort_tool">Gender<span class="caret"></span></button></a></th>
						<th width="<?php echo $size."%"; ?>" style="text-align:center"><a ng-click="sort_by('date_of_birth')"><button class="sort_tool">Date of Birth <span class="caret"></span></button></a></th>	
						<th width="<?php echo $size."%"; ?>" style="text-align:center"><a ng-click="sort_by('marital_status')"><button class="sort_tool">Marital Status <span class="caret"></span></button></a></th>	
						<th width="<?php echo $size."%"; ?>" style="text-align:center"><a ng-click="sort_by('creation_time | asDate')"><button class="sort_tool">Registered Date <span class="caret"></span></button></a></th>
						<th width="<?php echo $size."%"; ?>" style="text-align:center"><a ng-click="sort_by('address_province')"><button class="sort_tool">Address <span class="caret"></span></button></a></th>		
						<th width="<?php echo $size."%"; ?>" style="text-align:center"><a ng-click="sort_by('holiday')"><button class="sort_tool">Holiday<span class="caret"></span></button></a></th>							
						<th width="<?php echo $size."%"; ?>" style="text-align:center"><a ng-click="sort_by('device_model')"><button class="sort_tool">Device <span class="caret"></span></button></a></th>						
					</tr>
					</thead>				
					<tbody scroll>
						<tr ng-repeat="x in filtered = ( search_list | filter:query) | orderBy:predicate:reverse ">
							<td width="<?php echo $headSize; ?>"><a href="#" userdata="{{x.user_id}} " popup-user data-toggle="modal" data-target=".bs-example-modal-lg" index="{{ $index }}" class="user_button">{{ (x.name == null) ? '-' : x.name}}</a></td>
							<td width="<?php echo $size."%"; ?>">{{ (x.email == null || x.email == '-') ? '-' : x.email }}</td>
							<td width="<?php echo $size."%"; ?>">{{ (x.phone_number == null || x.phone_number == '-') ? '-' : x.phone_number }}</td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center"><capital>{{ (x.gender == null || x.gender == '-') ? '-' : x.gender }}</capital></td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center">{{ (x.date_of_birth == null || x.date_of_birth.trim() == '') ? '-' : (x.date_of_birth | asDate | date:'dd MMM yyyy') }}</td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center"><capital><strong>{{ (x.marital_status == null || x.marital_status.trim() == '') ? '-' : x.marital_status }}</strong></capital><br/>{{ (x.marital_kid_count > 0) ? x.marital_kid_count + ' Child(s)' : '-'}}</td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center">{{ (x.creation_time == null || x.creation_time.trim() == '') ? '-' : (x.creation_time | asDate | date:'dd MMM yyyy HH:mm') }}</td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center"><capital>{{ (x.address_province == null) ? '-' : x.address_province }}</capital></td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center"><capital>{{ (x.holiday == null) ? '-' : x.holiday }}</capital></td>
							<td width="<?php echo $size."%"; ?>" style="text-align:center"><capital><strong>{{ (x.device_name == null) ? '-' : x.device_name}}</strong></capital><br/><capital>{{ (x.device_model == null) ? '-' : x.device_model}}</capital><br/>{{ (x.imei == null) ? '-' : x.imei}}</td>
						</tr>
					</tbody>
				</table>
				
				</div>
					
				<div class="bg-loading">
					<div class="loading-text">
					<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="25px" height="25px"/>  &nbsp; &nbsp; <b>Loading...</b>
					</div>
				</div>	
			</div>
			<center>
			<div class="bg-log-loading" style="display:block">
				<div class="loading-text">
					<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="75px" height="75px"/><br/><h3><b>Loading...</b></h3>
				</div>
			</div>
			</center>
			</div>
		</div>
		</div>
	</div>
	<?php echo $this->render("includes/custslime/devicebox.phtml");?>
	<?php echo $this->render("includes/custslime/downloadbox.phtml");?>
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/sgift/custggi.js"); ?>