<?php echo $this->doctype(); ?>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Page Not Found</title>
	<?php echo $this->render("includes/script.phtml");?>
  </head>
  
  <body>
	<br/><br/><br/><br/>
	<div class="col-lg-5 col-md-5 col-sm-5 col-xs-5" id="errorpage">
	<div class="panel panel-primary">
		<div class="panel-heading style="padding:10px;">
			<a href="<?php echo $this->baseUrl;?>">
			<img src="<?php echo $this->baseUrl ?>/assets/images/samsung-white.png" class="img-responsive" alt="Samsung"/>
			</a>
		</div>
		<div class="panel-body">
			<div class="form-group">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<h1><font color="#4385cb"><b>Page Not Found.</b></font></h1><br>
				<p><h4><font color="#4385cb">Sorry, but the page that you're asking for does not seem to exist.</font></h4></p>
				<br />
				</div>
			</div>
		</div>
	</div>
	</div>
	
  </body>
</html>