<?php echo $this->doctype(); ?>
<html>
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl."/assets/maintenance/css/maintainance.css")
								->headLink(array('rel' => 'shortcut icon','href'=> $this->baseUrl."/favicon/favicon.png", 'PREPEND')); ?>
</head>
<body>
	<div class="bg">
		<div class="img-container"><img src="<?php echo $this->baseUrl; ?>/assets/maintenance/images/icon-maintainance.png"></img></div>
	</div>
	<div class="content">
	<span class="maintainance-title">Sorry, our site is under maintenance.</span><br/><br/>
	<div class="divider"></div>
	<br/>
	<span class="maintainance-tag">Please come later.</span>
	</div>
</body>
</html>