<?php echo $this->doctype();?>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?php echo $this->headTitle();?>
		<?php echo $this->render("includes/script.phtml"); ?>
	</head>
	<body>
	
		<br><br><br><br><br>
	
		<div class="form-group">
		<div class="col-sm-offset-3 col-sm-5">
			<img src="<?php echo $this->baseUrl ?>/assets/images/success.png" class="img-responsive" alt="Submitted Successfully" align="middle" />
			<br />
		</div>
		</div>
		
		<div class="form-group">
		<div class="col-sm-offset-3 col-sm-5">
			<h3><font color="#4385cb">The data has been submitted successfully.</font></h3>
			<br />
		</div>
		</div>
		
		<div class="form-group">
		<div class="col-sm-offset-3 col-sm-2">
			<a href="<?php echo $this->baseUrl;?>"><button type="button" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-circle-arrow-right"></span> &nbsp;Continue</button></a>
		</div>
		</div>

	</body>
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/login.js"); ?>
