<?php echo $this->doctype();?>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?php echo $this->headTitle();?>
		<?php echo $this->render("includes/script.phtml"); ?>
	</head>
	<body class='bg-gray'>
	
	<br><br><br><br><br>

	<div class="confirm-content">
	<center><img src='http://reporting.srinapps.com/public/assets/img/logo20.png' width='30%'/></center><br/>
	<div style='border-top:1px solid #e4e4e4;
	padding-top:5px;
	padding-bottom:5px;'>
	</div>
		<div class="form-group">

			<img src="<?php echo $this->baseUrl ?>/assets/images/success.png" alt="Submitted Successfully" align="middle" width="50%"/>
			<br />

		</div>
		
		<div class="form-group">
		
			<h4><font color="#4385cb">Your email has changed. Please check your new email.</font></h4>
			<br />

		</div>
		

	</body>
</html>
