<?php echo $this->doctype();?>
<html>
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>
<body class="bd_g_slime bd_slime_dashboard">
	<?php echo $this->render("includes/header.phtml"); ?>
	
	<div class="ch-container">
		<div class="row">
	   
		<!-- left menu starts -->
		<?php echo $this->render("includes/menu.phtml"); ?>
		<?php echo $this->render("includes/hidden.phtml"); ?>
		
		<div id="content" class="col-lg-12 col-sm-12 push">
			<?php
				$crumb = array("Home" => $this->baseUrl,
								"S Lime" => "active",
								"Slime Dashboard" => "active");
				$array = array(
								"item" => $crumb,
								"class" => "col-lg-12",
								"style" => "padding-right:15px"
								);
				echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
			?>
			
			<div class="col-sm-12">
				<div class="panel panel-default">
				<div class="panel-body">
					<h1>&nbsp;&nbsp;<?php echo $this->attr->title; ?></h1><hr/>
					
					<div class="clear"></div>
					<div class="col-sm-12">
						<div class="pull-right"><p style="color:#d9534f;"<h5><i>*)Last update data on <strong><?php echo date_format($this->lastGoogleUpdate,'d M Y'); ?></strong>.</i></h5></p></div>
					</div>
					<div class="row">
					<?php
						foreach($this->dashboardData as $data) :
					?>
						<div class="col-lg-3 col-md-6">
							<div class="panel panel-red">
								<div class="panel-heading">
									<div class="row">
										<div class="col-xs-3">
											<i class="fa fa-download fa-5x"></i>
										</div>
										<div class="col-xs-9 text-right">
											<div class="huge"><?php $activeInstall = $data->total_install - $data->total_uninstall; echo number_format($activeInstall,0,".",","); ?></div>
											<div>Active Installs</div>
										</div>
									</div>
								</div>
								<a href="<?php echo $this->baseUrl;?>/<?php echo $data->projectLink;?>/installs">
									<div class="panel-footer">
										<span class="pull-left">View Details</span>
										<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
										<div class="clearfix"></div>
									</div>
								</a>
							</div>
						</div>
						<div class="col-lg-2 col-md-6">
							<div class="panel panel-yellow">
								<div class="panel-heading">
									<div class="row">
										<div class="col-xs-3">
											<i class="fa fa-warning fa-5x"></i>
										</div>
										<div class="col-xs-9 text-right">
											<div class="huge"><?php echo $data->total_error; ?></div>
											<div>Error Reports</div>
										</div>
									</div>
								</div>
								<a href="<?php echo $this->baseUrl;?>/<?php echo $data->projectLink;?>/errorreport">
									<div class="panel-footer">
										<span class="pull-left">View Details</span>
										<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
										<div class="clearfix"></div>
									</div>
								</a>
							</div>
						</div>
						<div class="col-lg-2 col-md-6">
							<div class="panel panel-green">
								<div class="panel-heading">
									<div class="row">
										<div class="col-xs-3">
											<i class="fa fa-exchange fa-5x"></i>
										</div>
										<div class="col-xs-9 text-right">
											<div class="huge"><?php echo $data->total_carrier;?></div>
											<div>Total Carrier</div>
										</div>
									</div>
								</div>
								<a href="<?php echo $this->baseUrl;?>/<?php echo $data->projectLink;?>/carrier">
									<div class="panel-footer">
										<span class="pull-left">View Details</span>
										<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
										<div class="clearfix"></div>
									</div>
								</a>
							</div>
						</div>
						<div class="col-lg-2 col-md-6">
							<div class="panel panel-blue">
								<div class="panel-heading">
									<div class="row">
										<div class="col-xs-3">
											<i class="fa fa-mobile fa-5x"></i>
										</div>
										<div class="col-xs-9 text-right">
											<div class="huge"><?php echo $data->total_devices;?></div>
											<div>Total Device</div>
										</div>
									</div>
								</div>
								<a href="<?php echo $this->baseUrl;?>/<?php echo $data->projectLink;?>/devices">
									<div class="panel-footer">
										<span class="pull-left">View Details</span>
										<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
										<div class="clearfix"></div>
									</div>
								</a>
							</div>
						</div>
						<div class="col-lg-3 col-md-6">
							<div class="panel panel-purple">
								<div class="panel-heading">
									<div class="row">
										<div class="col-xs-3">
											<i class="fa fa-thumbs-up fa-5x"></i>
										</div>
										<div class="col-xs-9 text-right">
											<div class="huge"><?php echo $data->rating; ?></div>
											<div>Total Rating</div>
										</div>
									</div>
								</div>
								<a href="<?php echo $this->baseUrl;?>/<?php echo $data->projectLink;?>/review">
									<div class="panel-footer">
										<span class="pull-left">View Details</span>
										<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
										<div class="clearfix"></div>
									</div>
								</a>
							</div>
						</div>
					<?php
						endforeach;
					?>
					</div>
					
					<div class="row">
						<div class="col-lg-8">
						
							<!-- REVENUE CHART -->
							<div class="panel panel-grey">
								<div class="panel-heading">
									<i class="fa fa-bar-chart-o fa-fw" style="padding-top:10px;"></i> Monthly Revenue Chart
									
									<div class="btn-group pull-right">	
										<button id="export" class="btn btn-default"><i class="glyphicon glyphicon-folder-open"></i> &nbsp;Export CSV</button>
										<button type="button" data-time="daily" class="btn btn-default filter_button" value="daily">Daily</button>
										<button type="button" data-time="weekly" class="btn btn-default filter_button" value="weekly">Weekly</button>
										<button type="button" data-time="monthly" class="btn btn-default filter_button active" value="monthly">Monthly</button>
									</div>
									<div class="clear"></div>
								</div>
								<!-- /.panel-heading -->
								<div class="panel-body" id="monthly_graph">
									
								</div>
							</div>
							<!-- -->
							
							<!-- REVENUE TABLE -->
							<div class="panel panel-default">
								<div class="panel-heading">
									<i class="fa fa-table fa-fw" style="padding-top:10px;"></i> Monthly Revenue Table
								</div>
								<!-- /.panel-heading -->
								<div class="panel-body">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>Publisher</th>
												<th style="text-align:right">Last Month</th>
												<th style="text-align:right">This Month</th>
												<th style="text-align:right">All Month</th>
											</tr>
										</thead>
										<tbody>
											<?php
												$total_last = 0; $total_this = 0; $total_all = 0;
												foreach($this->revenueTable as $tbl) : ?>
											<tr>
												<td><?php echo $tbl->name;?></td>
												<td align="right">Rp. <?php echo number_format($tbl->last_month, 0, ".",",");?>,-</td>
												<td align="right">Rp. <?php echo number_format($tbl->this_month, 0, ".",",");?>,-</td>
												<td align="right">Rp. <?php echo number_format($tbl->all_month, 0, ".",",");?>,-</td>
												<?php 
													$total_last += $tbl->last_month;
													$total_this += $tbl->this_month;
													$total_all += $tbl->all_month;
												?>
											</tr>
											<?php endforeach; ?>
										</tbody>
										<tfoot>
											<tr>
												<th>Total</th>
												<th style="text-align:right">Rp. <?php echo number_format($total_last, 0, ".",",");?>,-</th>
												<th style="text-align:right">Rp. <?php echo number_format($total_this, 0, ".",",");?>,-</th>
												<th style="text-align:right">Rp. <?php echo number_format($total_all, 0, ".",",");?>,-</th>
											</tr>
										</tfoot>
									</table>
								</div>
							</div>
							
							<!-- Monthly Revenue Bar -->
							<div class="col-lg-6" style="padding-left:0px;">
							<div class="panel panel-grey">
								<div class="panel-heading">
									<i class="fa fa-pie-chart fa-fw"></i> Monthly Publisher Revenue
								</div>
								<div class="panel-body"  >
									<div id="monthly_revenue" style="width:100%;">
									</div>
								</div>
							</div>
							</div>
							<!-- -->
							<!-- Publisher Download Bar -->
							<div class="col-lg-6" style="padding-right:0px;">
							<div class="panel panel-grey">
								<div class="panel-heading">
									<i class="fa fa-pie-chart fa-fw"></i> Monthly Publisher Download
								</div>
								<div class="panel-body">
									<div id="monthly_download" style="width:100%;">
									</div>
								</div>
							</div>
							</div>
							<!-- -->
						</div>
						
						
						<div class="col-lg-4">
						
							<div class="panel panel-grey">
								<div class="panel-heading">
									<i class="fa fa-trophy fa-fw"></i> Top 5 Magazines
								</div>
								<!-- /.panel-heading -->
								<div class="panel-body">
									<div class="table-responsive">
                                        <table class="table table-bordered table-hover table-striped">
                                            <thead>
                                                <tr>
                                                    <th style="text-align:center">No.</th>
                                                    <th>Magazine</th>
													<th style="text-align:center">Publisher</th>
                                                    <th style="text-align:right">Total Download</th>
                                                </tr>
                                            </thead>
                                            <tbody>
												<?php
												if (sizeof($this->top5Magz) > 0) {
												$no = 1;
												foreach($this->top5Magz as $data) : ?>
													<tr>
														<td align="center"><?php echo $no; ?></td>
														<td><?php echo $data->name; ?></td>
														<td align="center"><?php echo $data->publisher; ?></td>
														<td align="right"><a href="<?php echo $this->baseUrl;?>/download?product=<?php echo $data->name; ?>"><strong><?php echo number_format($data->download,0,".",","); ?></strong></a></td>
													</tr>
												<?php 
												$no++;
												endforeach; 
												} else { ?>
													<tr>
														<td colspan="4" align="center">
															<span class="glyphicon glyphicon-exclamation-sign"></span> &nbsp;<strong>No Magazines Found..</strong>
														</td>
													</tr>
												<?php } ?>
												<?php if (sizeof($this->top5Magz) > 0) { ?>
													<tr>
														<td colspan="4" align="center">
															<a target="_new" href="<?php echo $this->baseUrl;?>/favourite?cat=<?php echo $this->config->slime->category->magazine;?>" class="btn btn-default col-lg-12"><span class="fa fa-file-text"></span> &nbsp;<strong>View All Magazines</strong></a>
														</td>
													</tr>
												<?php } ?>
                                            </tbody>
                                        </table>
                                    </div>
								</div>
							</div>
							<!-- -->
							
							<div class="panel panel-grey">
								<div class="panel-heading">
									<i class="fa fa-trophy fa-fw"></i> Top 5 Newspapers
								</div>
								<!-- /.panel-heading -->
								<div class="panel-body">
									<div class="table-responsive">
                                        <table class="table table-bordered table-hover table-striped">
                                            <thead>
                                                 <tr>
                                                    <th style="text-align:center">No.</th>
                                                    <th>Newspaper</th>
													<th style="text-align:center">Publisher</th>
                                                    <th style="text-align:right">Total Download</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php 
												if (sizeof($this->top5News) > 0) 
												{
												$no = 1;
												foreach($this->top5News as $data) : ?>
													<tr>
														<td align="center"><?php echo $no; ?></td>
														<td><?php echo $data->name; ?></td>
														<td align="center"><?php echo $data->publisher; ?></td>
														<td align="right"><a href="<?php echo $this->baseUrl;?>/download?product=<?php echo $data->name; ?>"><strong><?php echo number_format($data->download,0,".",","); ?></strong></a></td>
													</tr>
												<?php 
												$no++;
												endforeach; 
												} else { ?>
													<tr>
														<td colspan="4" align="center">
															<span class="glyphicon glyphicon-exclamation-sign"></span> &nbsp;<strong>No Newspaper Found..</strong>
														</td>
													</tr>
												<?php } ?>
												<?php if (sizeof($this->top5News) > 0) { ?>
													<tr>
														<td colspan="4" align="center">
															<a target="_new" href="<?php echo $this->baseUrl;?>/favourite?cat=<?php echo $this->config->slime->category->newspaper;?>" class="btn btn-default col-lg-12"><span class="fa fa-newspaper-o"></span> &nbsp;<strong>View All Newspapers</strong></a>
														</td>
													</tr>
												<?php } ?>
                                            </tbody>
                                        </table>
                                    </div>
								</div>
								<!-- -->
							</div>
							
							<div class="panel panel-grey">
								<div class="panel-heading">
									<i class="fa fa-trophy fa-fw"></i> Top 5 Books
								</div>
								<!-- /.panel-heading -->
								<div class="panel-body">
									<div class="table-responsive">
                                        <table class="table table-bordered table-hover table-striped">
                                            <thead>
                                                 <tr>
                                                    <th style="text-align:center">No.</th>
                                                    <th>Book</th>
													<th style="text-align:center">Publisher</th>
                                                    <th style="text-align:right">Total Download</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                               <?php 
												if (sizeof($this->top5Books) > 0) 
												{
												$no = 1;
												foreach($this->top5Books as $data) : ?>
													<tr>
														<td align="center"><?php echo $no; ?></td>
														<td><?php echo $data->name; ?></td>
														<td align="center"><?php echo $data->publisher; ?></td>
														<td align="right"><?php echo number_format($data->download,0,".",","); ?></td>
													</tr>
												<?php 
												$no++;
												endforeach; 
												} else { ?>
													<tr>
														<td colspan="4" align="center">
															<span class="glyphicon glyphicon-exclamation-sign"></span> &nbsp;<strong>No Books Found..</strong>
														</td>
													</tr>
												<?php } ?>
												<?php if (sizeof($this->top5News) > 0) { ?>
													<tr>
														<td colspan="4" align="center">
															<a target="_new" href="<?php echo $this->baseUrl;?>/favourite?cat=<?php echo $this->config->slime->category->book;?>" class="btn btn-default col-lg-12"><span class="fa fa-book"></span> &nbsp;<strong>View All Books</strong></a>
														</td>
													</tr>
												<?php } ?>
                                            </tbody>
                                        </table>
                                    </div>
								</div>
							</div>
							<!-- -->
							
							<div class="panel panel-default">
								<div class="panel-heading">
									<i class="fa fa-trophy fa-fw"></i> Top 5 Device Contribution
								</div>
								<!-- /.panel-heading -->
								<div class="panel-body">
									<div class="table-responsive">
										<table class="table table-hover table-striped">
											<thead>
												<tr>
													<th style="text-align:center;" width="50px">No.</th>
													<th width="320px">Device</th>
													<th style="text-align:right;">Revenue</th>
												</tr>
											</thead>
											<tbody>
												<?php 
												$no = 1; 
												foreach($this->top5Con as $data) : ?>
													<tr>
														<td align="center"><?php echo $no; ?></td>
														<td >Samsung <?php echo $data->name;?></td>
														<td align="right"><?php echo number_format($data->total,0,".",",");?></td>
													</tr>
												<?php 
												$no++;
												endforeach; ?>
											</tbody>
										</table>
									</div>
									<!-- /.list-group -->
									<!--<a href="#" class="btn btn-default btn-block">View All Alerts</a>-->
								</div>
								<!-- /.panel-body -->
							</div>
						</div>
					</div>
					<center>
					<div class="bg-log-loading" style="display:block">
						<div class="loading-text">
							<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="75px" height="75px"/><br/><h3><b>Loading...</b></h3>
						</div>
					</div>
					</center>
				</div>
				</div>
			</div>
		</div>
	</div> 
</body>
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/dashboard/slimedashboard.js"); ?>