<?php echo $this->doctype();?>
<html ng-app=UserApp>
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>
<body class="bd_user" ng-controller="userCtrl">
	<?php echo $this->render("includes/header.phtml"); ?>
	<?php echo $this->render("includes/hidden.phtml"); ?>
	
	<div class="ch-container">
		<div class="row">
	   
		<!-- left menu starts -->
		<?php echo $this->render("includes/menu.phtml"); ?>
		
		<div id="content" class="col-lg-12 col-sm-12 push">
			<?php
				$crumb = array("Home" => $this->baseUrl,
							   "Management" => "active",
							   "Manage Users" => "active");
				$array = array(
								"item" => $crumb,
								"class" => "col-lg-7",
								"style" => "padding-right:0px"
							  );
				echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
			?>

			<div class="col-lg-5" id="search-crumb" style="padding-left:0px;">
				<div class="col-lg-8 pull-right" id="search_container" style="padding-right:0px; padding-left:5px;">
				<form action="<?php echo $this->baseUrl;?>/user" method="GET" role="form" id="search-form">
					<div class="input-group">
						<span class="input-group-btn">
							<button type="button" class="btn btn-default search-btn" type="button" id="advanced_search_button">
								<span class="caret"></span><span class="sr-only">Toggle Dropdown</span>
							</button>
						</span>
						<input type="text" class="form-control" placeholder="Search..." name="q" id="input_search" value="<?php echo $this->param->q;?>">
						<span class="input-group-btn">
							<button class="btn btn-default" type="submit" ><span class="glyphicon glyphicon-search"></span></button>
						</span>
					</div><!-- /input-group -->
				</form>
				</div><!-- /.col-lg-4 col-lg-push-4-->
			</div>
			
			<div class="col-sm-6" >			
				<div class="advanced_search_container col-sm-10" id="advanced_search_container">
					<div class="panel panel-default">
					<div class ="panel-body" >
						<h3>Advance Search</h3><hr/>
						<form action="<?php echo $this->baseUrl;?>/user" method="GET" role="form" class="form-horizontal">
						<div class="form-horizontal">
						<div class="advanced-input-group">
							<div class="form-group">
								<label for="inputEmail3" class="col-sm-3 control-label">Username</label>
								<div class="col-sm-9">
								  <input type="text" class="form-control advanced-input" placeholder="Username" name="username" value="<?php echo $this->param->username;?>">
								</div>
							 </div>
							 <div class="form-group">
								<label for="inputEmail3" class="col-sm-3 control-label">Role</label>
								<div class="col-sm-9">
									<select id="role" name="role" class="form-control">
										<option value="">- All Role -</option>
										<?php foreach ($this->roleList as $role) : ?>
										<option value="<?php echo $role->roleID;?>"
										<?php echo ($role->roleID == $this->param->role) ? "selected" : ""; ?>
										><?php echo $role->roleName;?></option>
										<?php endforeach;?>
									</select>
								</div>
							 </div>
							 
							 <div class="form-group">
								<label for="inputEmail3" class="col-sm-3 control-label">Project</label>
								<div class="col-sm-9">
									<select class="form-control" id="project" name="project">
										<option value="">- All Project -</option>
										<?php foreach($this->projects as $project) : ?>
										<option value="<?php echo $project->projectName; ?>"
										<?php echo ($project->projectName == $this->param->project) ? "selected" : ""; ?>
										><?php echo $project->projectName;?></option>
										<?php endforeach; ?>
									</select>
								</div>
							 </div>
							 
							 <div class="form-group">
								<label for="inputEmail3" class="col-sm-3 control-label">Created Date</label>
								<div class="col-sm-9">
									<input type="text" class="form-control advanced-input date" placeholder="YYYY-MM-DD" name="created_date" value="<?php echo $this->param->created_date;?>">
								</div>
							 </div>
							 
							  <div class="form-group">
								<label for="inputEmail3" class="col-sm-3 control-label">Status</label>
								<div class="col-sm-9">
									<select name="active" id="active" class="form-control">
										<option value="">- All Status -</option>
										<option value="1" <?php echo ($this->param->active == 1) ? "selected" : ""; ?>>Active</option>
										<option value="0" <?php echo ($this->param->active == 0 && $this->param->active != "") ? "selected" : ""; ?>>Inactive</option>
									</select>
								</div>
							 </div>
							<button type="submit" class="btn btn-primary search-btn pull-right"><i class="glyphicon glyphicon-search"></i> &nbsp;Search</button>
						</div>
						</div>
						</form>
					</div>
					</div>
				</div>
				
			</div>
			<div class="col-sm-12">
				<div class="panel panel-default">
				
				<div class="panel-body">
				<div class="row">
				
					<div class="form-group pull-left form-inline" style="margin-left:15px;">
						<span class="pull-left lbl"><h5>&nbsp; <i class="glyphicon glyphicon-eye-open"></i> &nbsp;Showing &nbsp;<strong>{{users.length}}</strong>&nbsp; from 
						&nbsp;<strong>{{users.length | number:0}}</strong>&nbsp; data</h5></span>
					</div>
					
					<div class="form-group pull-right form-inline" style="margin-right:15px;">
						<?php
							if ($this->mySession->role == $this->config->role->id->superadmin) {
						?>
						<div class="float_left">
							<a href="<?php echo $this->baseUrl;?>/user/insert" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i>&nbsp; Insert User</a>
						</div>
						<?php 
							}
						?>&nbsp;&nbsp;
						
						<div class="form-group ">
							<div class="input-group ">
							  <div class="input-group-addon">
								<span class="glyphicon glyphicon-filter"></span>&nbsp;&nbsp;<span class="badge">{{filtered.length | number:0}}</span>
								</div>
							  <input class="form-control" ng-model="query[queryBy]" placeholder="Filter by...">
							</div>
						</div>
						<div class="form-group">
							<select class="form-control" ng-model="queryBy">
								<option value="$">All</option>
								<option value="username">Username</option>
								<option value="roleName">Role</option>
								<option value="projectName">Project</option>
								<option value="created_date">Created Date</option>
							</select>
						</div>
						
					</div>
				</div>	
					
					<div class='tb-test'>
						<table class="table table-striped">
							<thead>
								<tr>
									<th width="300px"><a href="#" ng-click="predicate = 'username'; reverse=!reverse">
										<button class="sort_tool">Username</button></a>
									</th>
									<th>
										<a href="#" ng-click="predicate = 'roleName'; reverse=!reverse"><button class="sort_tool">Role
										</button></a>
									</th>
									<th width="270px">
										<a href="#" ng-click="predicate = 'projectName'; reverse=!reverse"><button class="sort_tool">Project
										</button></a></th>
									<th >
										<a href="#" ng-click="predicate = 'created_date | asDate'; reverse=!reverse"><button class="sort_tool">Created Date
										</button></a>
									</th>
									<th width="100px">
										<center><a href="#" ng-click="predicate = 'active'; reverse=!reverse"><button class="sort_tool">Active
										</button></a></center>
									</th>
									<th><center>Action</center></th>
								</tr>
							</thead>
							<tbody>
								<tr ng-repeat="user in filtered = ( users | filter:query | filter:projectFilter ) | orderBy:predicate:reverse">
									<td>{{user.username}}</td>
									<td>{{user.roleName}}</td>
									<td>{{user.projectName}}</td>
									<td>{{user.created_date | asDate | date:'dd MMM yyyy - HH:mm'}}</td>
									<td align="center">
										<span ng-if="user.active==1" class="glyphicon glyphicon-ok green font-large"></span>
										<span ng-if="user.active==0" class="glyphicon glyphicon-remove red font-large"></span>
										<!-- <input type="checkbox" class="form-control" disabled ng-checked="user.active == 1"/> -->
									</td>
									<td align="center">
										<?php
											if ($this->mySession->role == $this->config->role->id->superadmin) {
										?>
											<a href="<?php echo $this->baseUrl;?>/user/edit?id={{user.userID}}" style="text-decoration:none;">
												<button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span>
												</button>
											</a>
											
											&nbsp;
											<button ng-disabled="user.userID == '<?php echo $this->mySession->id;?>'" ng-click="remove($event, user)" data-id="{{user.userID}}" type="button" class="btn btn-danger btn-delete">
											<span class="glyphicon glyphicon-trash"></span>
											</button>
										<?php 
											} else {
										?>
												<strong>- No Action Allowed -</strong>
										<?php 
											}
										?>
									</td>
								</tr>				
							</tbody>
						</table>
					</div>
				</div>
				</div>
			</div>
		</div>
	</div>
	</body>
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/user.js"); ?>