<?php echo $this->doctype();?>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml");?>
</head>
<body class="bd_changepass">
	<?php echo $this->render("includes/header.phtml"); ?>
	
	<div class="ch-container">
	<div class="row">
   
    <!-- left menu starts -->
	<?php echo $this->render("includes/menu.phtml"); ?>
	
	
	
	<div id="content" class="col-lg-12 col-sm-12 push">
	
	<?php
		$crumb = array("Home" => $this->baseUrl,
					   "Change Password" => "active");
		$array = array(
						"item" => $crumb,
						"class" => "col-lg-12",
						"style" => "padding-right:15px"
					  );
		echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
	?>
	
	<div class="col-sm-12">
		<!-- Content Placed here -->
	<div class="panel panel-primary">
	<div class="panel-heading">
		<h3><i class="glyphicon glyphicon-lock"></i> &nbsp;Change Password</h3>
		<hr/>
	</div>
	<div class="panel-body">
		<form role="role" action="<?php echo $this->baseUrl;?>/main/chkchange" method="POST">
		
			<div class="form-group">
			<div class="input-group">
				<!--<label for="oldpass" class="col-sm-2 control-label">Old Password:</label>-->
				<span class="input-group-addon">
					<span class="glyphicon glyphicon-lock"></span>
				</span>
				<input type="password" class="form-control" name="oldpass" placeholder="Old Password">
			</div>
			</div>
			<div class="form-group">
			<div class="input-group">
				<!--<label for="exampleInputPassword1">New Password:</label> -->
				<span class="input-group-addon">
					<span class="glyphicon glyphicon-lock"></span>
				</span>
				<input type="password" class="form-control" name="newpass" placeholder="New Password">
			</div>
			</div>
			<div class="form-group">
			<div class="input-group">
				<!--<label for="exampleInputFile">Confirm New Password:</label>-->
				<span class="input-group-addon">
					<span class="glyphicon glyphicon-lock"></span>
				</span>
				<input type="password" class="form-control" name="confirm" placeholder="Confirm New password">
			</div>
			</div>
			
			<div class="form-group">
				<label for="error">
					<font color="red"><?php echo $this->error;?></font>
				</label>
			</div>
			
			
			<button type="submit" class="btn btn-default">Submit</button>

		</form>
		
			<!-- <form class="form-horizontal" role="form" method="post" action="<?php echo $this->baseUrl; ?>/index/chklogin">
				<div class="form-group">
					<div class="input-group col-sm-offset-1 col-sm-10 ">
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-user"></span>
						</span>
						<input type="email" class="form-control" name="username" id="inputUsername" placeholder="Username" maxlength="30" />
					</div>
				</div>
				
				<div class="form-group">
					<div class="input-group col-sm-offset-1 col-sm-10 ">
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-lock"></span>
						</span>
						<input type="password" class="form-control" name="password" id="inputPass" placeholder="Password" maxlength="30" />
					</div>
				</div>
				
				<div class="form-group">
					<label for="inputUsername" class="col-sm-11 control-label">
						<a href="#forget_pass" data-toggle="modal" id="lnkforget">Forget Password</a><br>
					</label>
				</div>
				
				<div class="form-group">
					<div class="col-sm-offset-8 col-sm-3 control-label">
					  <button type="submit" class="btn btn-primary" value="submit">Submit</button>
					</div>
				</div>
			</form> -->
		
		
	</div>
	</div>
	</div>
	</div>
	</div>
	</div>
</body>

</html>