<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml");?>
</head>
<body>
<?php echo $this->render("includes/header.phtml"); ?>
<?php echo $this->render("includes/hidden.phtml"); ?>

<div class="ch-container">
	<div class="row">
   
    <!-- left menu starts -->
	<?php echo $this->render("includes/menu.phtml"); ?>
	
	<div id="content" class="col-lg-12 col-sm-12 push">
		<?php
			$crumb = array("Home" => "active");
			$array = array(
							"item" => $crumb,
							"class" => "col-lg-12",
							"style" => "padding-right:15px"
						  );
			echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
		?>
		
		<!-- Content Placed here -->
		<?php echo $this->render("includes/carousel.phtml"); ?>
		<?php echo $this->render("includes/passbox.phtml");?>
	</div>
</div>
</body>
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/check_first.js");?>