<!-- Detail Pop Up -->
<!-- Download History -->
<div class="modal fade" id="downloadHistory">
  <div class="modal-dialog" style="width:900px">
	<div class="modal-content">
		<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h3>&nbsp;<span class="glyphicon glyphicon-download"></span> &nbsp;Download History</h3>
		</div>
		
		<div class ="modal-body" >
			<div class="form-group pull-right form-inline" style="margin-right:15px;">
				<div class="form-group" id="filter-textbox">
					<div class="input-group ">
					  <div class="input-group-addon">
						<span class="glyphicon glyphicon-filter"></span>&nbsp;&nbsp;<span class="badge">{{filtered_data.length | number:0}}</span>
					  </div>
						<input class="form-control" ng-model="queryPopUp[queryByPopUp]" placeholder="Filter by" >
					</div>
				</div>
				<div class="form-group" id="filter-option">
					<select class="form-control" ng-model="queryByPopUp">
						<option value="$">All</option>
						<option value="id">Download ID</option>
						<option value="download_time">Date</option>
						<option value="name">User</option>
						<option value="device_model">IMEI</option>
						<option value="download_url">URL</option>
					</select>		
				</div>
			</div>
			<div class="clear"></div>
		<div class="form-horizontal">
			<div class="send_group">
					
			<table class="table table-striped" id="doug-neiner-five" style="width:100%" >	
				<thead>
				<tr>
					<th width="120px"><a ng-click="sort_c_by('id')"><button class="sort_tool">Download ID</button></a></th>
					<th width="160px"><a ng-click="sort_c_by('download_time')"><button class="sort_tool">Date</button></a></th>
					<th width="180px"><a ng-click="sort_c_by('name')"><button class="sort_tool">User</button></a></th>
					<th width="210px"><a ng-click="sort_c_by('device_model')"><button class="sort_tool">Device / IMEI</button></a></th>
					<th width="200px"><a ng-click="sort_c_by('download_url')"><button class="sort_tool">URL</button></a></th>					
				</tr>
				</thead>				
				<tbody>
					<tr ng-if="downloadData.length <= 0">
						<td colspan="5" align="center">
							<span class="glyphicon glyphicon-exclamation-sign"></span> &nbsp;<strong>No History Found...</strong>
						</td>
					</tr>
					<tr ng-repeat="h in filtered_data = ( downloadData| filter:queryPopUp )| orderBy:predicate_c:reverse_c">
						<td width="120px" align="center">{{h.id}}</td>
						<td width="160px">{{h.download_time | asDate | date:'dd MMM yyyy HH:mm:ss'}}</td>
						<td width="180px">{{h.name}}</td>
						<td width="210px">{{h.device_model}}<br/>
							{{h.device_identifier}}</td>
						<td width="200px">
							{{ ( h.download_url == null  || h.download_url.trim() == '') ? '-' : h.download_url}}
						</td>
					</tr>
				</tbody>
			</table>
			</div>
		</div>
		</div>
	</div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

