<!-- Detail Pop Up -->
<!-- Product Box -->
<div class="modal fade" id="productBox">
  <div class="modal-dialog" style="width:900px">
	<div class="modal-content">
		<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h3>&nbsp;<span class="glyphicon glyphicon-book"></span> &nbsp;Content Detail</h3>
		</div>
		
		<div class ="modal-body" >
		<div role="tabpanel">
		 <ul class="nav nav-tabs" role="tablist">
			<li class="active tab" id="tab_detail" data-preview = "detail"><a href="#detail"  data-toggle="tab">Detail</a></li>
			<li class="tab" id="tab_preview" data-preview = "preview"><a href="#preview"  role="tab" data-toggle="tab">Preview</a></li>
		  </ul>
		  <div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="frm_detail">
				<div class="form-horizontal pad-detail">
				<form role="form">
				 <div class="promo_content">
					<div class="form-group">
						<label class="col-sm-3 control-label" for="inputEmail3">Product ID</label>
						<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{detailData.id}}</label>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label" for="inputEmail3">Product Name</label>
						<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{detailData.name}}</label>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label" for="inputEmail3">Publication Group</label>
						<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{detailData.group}}</label>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label" for="inputEmail3">Category</label>
						<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{(detailData.category == null || detailData.category.trim() == '') ? '-' : detailData.category}}</label>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label" for="inputEmail3">Publisher</label>
						<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{detailData.author}}</label>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label" for="inputEmail3">Cover</label>
						<label class="col-sm-9 control-label no-bold" for="inputEmail3">
							<img  ng-if="detailData.cover == null || detailData.cover.trim() == ''" src='<?php echo $this->baseUrl;?>/assets/images/no_image.jpg' style='border:thin solid silver;' height="270px"/>
							<img  ng-if="detailData.cover != null && detailData.cover.trim() != ''" src='http://s-lime.com/static/public/{{detailData.cover}}' style='border:thin solid silver;' height="300px"/>
						</label>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label" for="inputEmail3">Price</label>
						<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{detailData.price | number : 0}},-</label>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label" for="inputEmail3">Release Frequency</label>
						<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{ (detailData.freq == null || detailData.freq.trim() == '') ? '-' : detailData.freq }}</label>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label" for="inputEmail3">File Type</label>
						<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{ detailData.doc_type}}</label>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label" for="inputEmail3">Page Count</label>
						<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{ detailData.page_count}}</label>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label" for="inputEmail3">Sypnosis</label>
						<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{detailData.synopsis}}</label>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label" for="inputEmail3">Status</label>
						<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{detailData.status}}</label>
					</div>
				</form>
			</div>
			</div>
			
		  </div>
		  <div role="tabpanel" class="tab-pane" id="frm_preview">
				<div class="preview_image" style="padding:20px 30px 15px 30px" >
					<img ng-repeat="img in previewData" class="img-detail" ng-src="http://s-lime.com/static/public/{{img.file}}" height="320px" />
				</div>
			</div>
		</div>
		</div>
		</div>
	</div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->