<?php echo $this->doctype();?>
<html ng-app="myAppSgift">
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>
<body class="bd_g_sgift bd_ggi_promo" >
	<?php echo $this->render("includes/header.phtml"); ?>
	<?php echo $this->render("includes/hidden.phtml"); ?>
	<div class="ch-container">
	<div class="row">
	   
	<!-- left menu starts -->
	<?php echo $this->render("includes/menu.phtml"); ?>
			
	<div id="content" class="col-lg-12 col-sm-12 push">
		<?php
			$crumb = array("Home" => $this->baseUrl,
							"Galaxy Gift ID" => "active",
							"Promo &amp; Detail" => "active");
			$array = array(
							"item" => $crumb,
							"class" => "col-lg-7",
							"style" => "padding-right:0px"
							);
			echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
		?>
		<div id = "app_top" ng-controller="searchCrtl">
		<div class="col-lg-5" id="search-crumb" style="padding-left:0px;">
			<div class="col-lg-8 pull-right" id="search_container" style="padding-right:0px; padding-left:5px;">
				<form action="<?php echo $this->baseUrl;?>/productggi/index" method="GET" role="form" id="search-form">
					<div class="input-group">
					<span class="input-group-btn">
						<button type="button" class="btn btn-default search-btn" type="button" id="advanced_search_button">
						<span class="caret"></span><span class="sr-only">Toggle Dropdown</span>
						</button>
					</span>
					<input type="text" class="form-control" placeholder="Search.." name="q" id="input_search" value="<?php echo $this->param->q;?>">
					<span class="input-group-btn">
						<button class="btn btn-default" type="submit" ><span class="glyphicon glyphicon-search"></span></button>
					</span>
					</div><!-- /input-group -->
				</form>
			</div><!-- /.col-lg-4 col-lg-push-4-->
			
			<div class="btn-group pull-right" id="export_csv">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
				<span class="glyphicon glyphicon-folder-open"></span> &nbsp; Export CSV &nbsp;&nbsp;<span class="caret"></span>
				</button>
				<ul class="dropdown-menu" role="menu">
					<li><a ng-click="exportCurrent($event)" href="#">Export Filtered Document</a></li>
					<li><a ng-click="exportAll($event)" href="#">Export All Document</a></li>
					<li><a ng-click="export($event)" href="#">Export </a></li>
				</ul>
			</div>
		</div>
		
		<div class="col-sm-6" ><div class="advanced_search_container col-sm-10" id="advanced_search_container"><div class="panel panel-default">  
			<div class ="panel-body">
			<h3>Advanced Search</h3><hr/>
				<form action="<?php echo $this->baseUrl;?>/productggi/index" method="GET" role="form" class="form-horizontal" id="advance-search-form">
					<div class="form-horizontal"><div class="advanced-input-group">
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Merchant Name</label>
							<div class="col-sm-9">
							<input type="text" class="form-control advanced-input" placeholder="Merchant name" name="merchant_name" id="merchant_name" value="<?php echo $this->param->merchant_name;?>">
							</div>
						</div>
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Segment</label>
							<div class="col-sm-9">
								<label class="chk"><input type="checkbox" id="segment2" name="segment[]" value="2" class="chk_item" <?php echo ( in_array( 2, $this->param->segment) ) ? "checked" : "";?> />&nbsp;Premium</label>
								<label class="chk"><input type="checkbox" id="segment1" name="segment[]" value="1" class="chk_item" <?php echo ( in_array( 1, $this->param->segment) ) ? "checked" : "";?>/>&nbsp;New Entry</label>
								<label class="chk"><input type="checkbox" id="segment3" name="segment[]" value="3" class="chk_item" <?php echo ( in_array( 3, $this->param->segment) ) ? "checked" : "";?>/>&nbsp;Tablet</label>
							</div>
						</div>
						<button class="btn btn-primary search-btn pull-right" id="adv-button"><i class="glyphicon glyphicon-search"></i> &nbsp;Search</button>
					</div></div>
				</form>
			</div>
		</div></div></div>
		
		<div class="col-sm-12">
			<div class="panel panel-default">
			<div class="panel-body" style="padding-bottom:0px;">
					
			<div class="row">
			
			<div class="panel panel-primary user_detail_container">
				<div class="panel-heading">
					<button type="button" class="close" data-dismiss="modal" id="close_user"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h3 class="panel-title">User Details</h3>
				</div>
				<div class="panel-body" id="detail_user">
					Panel content
				</div>
			</div>
			
			<!-- -->
			
			<div class="form-group pull-left form-inline" style="margin-left:15px;">
				<form class="form-inline" role="form">
				<span class="pull-left lbl"><h5>&nbsp; <i class="glyphicon glyphicon-eye-open"></i> &nbsp;Showing &nbsp;<strong>{{search_list.length | number:0}}</strong>&nbsp; from 
				&nbsp;<strong>{{totalData | number:0}}</strong>&nbsp; data</h5></span>
				</form>
			</div>
			
			<div class="form-group pull-right form-inline" style="margin-right:15px;" id="filter-textbox">
				
				<div class="form-group ">
					<div class="input-group ">
					  <div class="input-group-addon">
						<span class="glyphicon glyphicon-filter"></span>&nbsp;&nbsp;<span class="badge">{{filtered.length}}</span>
					  </div>
					  <input class="form-control" ng-model="query[queryBy]" placeholder="Type the filter here.." >
					</div>
				</div>
				
				<div class="form-group" id="filter-option">
					<select class="form-control" ng-model="queryBy_detail" >
						<option value="$">All</option>
						<option value="merchant">Merchant</option>
						<option value="jumlah_promo">Promo</option>
						<option value="jumlah_voucher">Vouchers</option>
						<option value="jumlah_redeem">Redeems</option>
						<option value="jumlah_claim">Claims</option>
						<option value="jumlah_claim">Average Minutes</option>
					</select>		
				</div>
				
				&nbsp; &nbsp;&nbsp;
				
				
			</div>
			<div class="clear"></div>
	
			<div class='tb-test'>
			<div class="t-c">
				<table class="table table-striped merchant_table" id="transaction_table">	
					<thead>
					<tr>
						<th width="350px"><a ng-click="sort_by('merchant')"><button class="sort_tool">Merchant</button></a></th>
						<th width="12%" style='text-align:center'><a ng-click="sort_by('jumlah_promo')"><button class="sort_tool">Promo <span class="caret"></span></button></a></th>
						<th width="12%" style='text-align:center'><a ng-click="sort_by('jumlah_voucher')"><button class="sort_tool">Vouchers <span class="caret"></span></button></a></th>
						<th width="12%" style='text-align:center'><a ng-click="sort_by('jumlah_redeem | number : 0')"><button class="sort_tool">Redeems <span class="caret"></span></button></a></th>
						<th width="12%" style='text-align:center'><a ng-click="sort_by('jumlah_claim | number : 0');"><button class="sort_tool">Claims <span class="caret"></span></button></a></th>
						<th width="12%" style='text-align:center'><a ng-click="sort_by('redeem_ratio_m');"><button class="sort_tool">Redeems Ratio <span class="caret"></span></button></a></th>
						<th width="12%" style='text-align:center'><a ng-click="sort_by('claim_ratio_m');"><button class="sort_tool">Claims Ratio <span class="caret"></span></button></a></th>
						<th width="12%" style='text-align:center'><a ng-click="sort_by('average_minute');"><button class="sort_tool">Average Min <span class="caret"></span></button></a></th>					
					</tr>
					</thead>				
					<tbody scroll>
						<tr ng-repeat="x in filtered = ( search_list | filter:query) | orderBy:predicate:reverse  ">
							<td width="360px" ><a class="cursor" ng-click="loadDetail($event, x)" ><span ng-bind-html="trustHtml(x.merchant)"></span></a></td>
							<td width="12%" align='center'>{{ (x.jumlah_promo == null) ? 0 : x.jumlah_promo | number:0  }}</td>
							<td width="12%" align='center'>{{ (x.jumlah_voucher == null) ? 0 : x.jumlah_voucher | number:0 }}</td>
							<td width="12%" align='center'>{{ (x.jumlah_redeem == null) ? 0 : x.jumlah_redeem | number:0  }}</td>
							<td width="12%" align='center'>{{ (x.jumlah_claim == null) ? 0 : x.jumlah_claim | number:0 }}</td>
							<td width="12%" align='center'>{{ x.redeem_ratio_m = (x.jumlah_redeem == null) ? 0 : ((x.jumlah_redeem / x.jumlah_voucher) * 100| number:2)  }} %</td>
							<td width="12%" align='center'>{{ x.claim_ratio_m = (x.jumlah_claim == null) ? 0 : ((x.jumlah_claim / x.jumlah_voucher) * 100 | number:2) }} %</td>
							<td width="12%" align='center'>{{ (x.average_minute == null) ? "-" : (x.average_minute | number:2)}} </td>
						</tr>
					</tbody>
				</table>
			</div>
			<center>
			<div class="bg-log-loading" style="display:block;">
				<div class="loading-text">
					<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="75px" height="75px"/><br/><h3><b>Loading...</b></h3>
				</div>
			</div>
			</center>
			</div>
			
			<!-- BAWAH -->
			<div id="div_detail" class="d_none">
			<div style="padding:20px">
				<legend>
					Detail Promo
				</legend>
			</div>
			
			
			<div class="col-lg-5 pull-right" id="search-crumb" style="margin-top:0px;">
				
				<div class="col-lg-8 pull-right" id="search_container" style="padding-right:0px; padding-left:5px;">
					<form action="<?php echo $this->baseUrl;?>/productggi/index" method="GET" role="form" id="search-form">
						<div class="input-group">
						<span class="input-group-btn">
							<button type="button" class="btn btn-default search-btn" type="button" id="advanced_search_button_detail">
							<span class="caret"></span><span class="sr-only">Toggle Dropdown</span>
							</button>
						</span>
						<input type="text" class="form-control" placeholder="Search.." name="q_detail" id="input_search_detail" value="<?php echo $this->param->q_detail;?>">
						<span class="input-group-btn">
							<button class="btn btn-default" type="submit" ><span class="glyphicon glyphicon-search"></span></button>
						</span>
						</div><!-- /input-group -->
					</form>
				</div><!-- /.col-lg-4 col-lg-push-4-->
				
				<div class="btn-group pull-right" id="export_csv">
					<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
					<span class="glyphicon glyphicon-folder-open"></span> &nbsp; Export CSV &nbsp;&nbsp;<span class="caret"></span>
					</button>
					<ul class="dropdown-menu" role="menu">
						<li><a ng-click="exportCurrent_detail($event)">Export Document to CSV</a></li>
					</ul>
				</div>
			</div>
			<div class="col-sm-6" ><div class="advanced_search_container col-sm-10" id="advanced_search_container_detail"><div class="panel panel-default">  
			<div class ="panel-body">
			<h3>Advanced Search</h3><hr/>
				<form  method="GET" role="form" class="form-horizontal" id="advance-search-form">
					<div class="form-horizontal"><div class="advanced-input-group">
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Merchant Name</label>
							<div class="col-sm-9">
							<input type="text" class="form-control advanced-input" placeholder="Merchant name" name="merchant_name_detail" id="merchant_name_detail" value="<?php echo $this->param->merchant_name_detail;?>">
							</div>
						</div>
						
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Promotion Name</label>
							<div class="col-sm-9">
							<input type="text" class="form-control advanced-input" placeholder="Promotion name" name="promotion_name_detail" id="promotion_name_detail" value="<?php echo $this->param->promotion_name_detail;?>">
							</div>
						</div>
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Segment</label>
							<div class="col-sm-9">
								<label class="chk"><input type="checkbox" id="segment2_detail" name="segment_detail[]" value="2" class="chk_item" <?php echo ( in_array( 2, $this->param->segment_detail) ) ? "checked" : "";?>/>&nbsp;Premium</label>							
								<label class="chk"><input type="checkbox" id="segment1_detail" name="segment_detail[]" value="1" class="chk_item" <?php echo ( in_array( 1, $this->param->segment_detail) ) ? "checked" : "";?>/>&nbsp;New Entry</label>
								<label class="chk"><input type="checkbox" id="segment3_detail" name="segment_detail[]" value="3" class="chk_item" <?php echo ( in_array( 3, $this->param->segment_detail) ) ? "checked" : "";?>/>&nbsp;Tablet</label>
							</div>
						</div>
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-3 control-label">Start-End Date</label>
							<div class="col-sm-9">
								<input type="text" class="form-control inline date"  name="start_date" id="start_date" value="<?php echo $this->param->start_date; ?>" placeholder="YYYY-MM-DD" style="width:48%" /> 
								-
								<input type="text" class="form-control inline date" style="width:48%" name="end_date" value="<?php echo $this->param->end_date; ?>" placeholder="YYYY-MM-DD" id="end_date" />
							</div>
						</div>
						<button type="button" class="btn btn-primary search-btn pull-right" id="adv-button" ng-click="loadDetail($event, '')"><i class="glyphicon glyphicon-search"></i> &nbsp;Search</button>
					</div></div>
				</form>
			</div>
			</div></div></div>
			<br/>
			<br/>
			<div class="clear"></div>
			<div class="form-group pull-left form-inline" style="margin-left:15px;">
					<form class="form-inline" role="form">
					<span class="pull-left lbl"><h5>&nbsp; <i class="glyphicon glyphicon-eye-open"></i> &nbsp;Showing &nbsp;<strong>{{search_list_detail.length | number:0}}</strong>&nbsp; from 
					&nbsp;<strong>{{totalData_detail | number:0}}</strong>&nbsp; data</h5></span>
					</form>
				</div>
			<div class="form-group pull-right form-inline" style="margin-right:15px;" id="filter-textbox">
				
				<div class="form-group ">
					<div class="input-group ">
					  <div class="input-group-addon">
						<span class="glyphicon glyphicon-filter"></span>&nbsp;&nbsp;<span class="badge">{{filtered_detail.length}}</span>
					  </div>
					  <input class="form-control" ng-model="query_detail[queryBy_detail]" placeholder="Type the filter here.." >
					</div>
				</div>
				
				<div class="form-group" id="filter-option">
					<select class="form-control" ng-model="queryBy_detail" >
						<option value="$">All</option>
						<option value="merchant">Merchant</option>
						<option value="promo_name">Promo Name</option>
						<option value="promo_id">Promo ID</option>
						<option value="start_time">Start</option>
						<option value="end_time">End</option>
						<option value="jumlah_voucher">Vouchers</option>
						<option value="jumlah_redeem">Redeems</option>
						<option value="total_claim">Claims</option>
						<option value="last_redeem_time">Last Redeem</option>
						<option value="minutes">Minutes</option>
						<option value="redeem_ratio">Redeem Ratio</option>
						<option value="claim_ratio">Claim Ratio</option>
					</select>		
				</div>
				
				
			</div>
			<div class="clear"></div>
			
			<div class='tb-test'>
			<div class="t-c">
				<table class="table table-striped merchant_table" id="merchant_table2">	
					<thead>
					<tr>
						<th width="300px"><a ng-click="sort_by_detail('merchant')"><button class="sort_tool">Merchant <span class="caret"></span></button></a></th>
						<th width="8%"><a ng-click="sort_by_detail('promo_name')"><button class="sort_tool">Promo Name <span class="caret"></span></button></a></th>
						<th width="8%"><a ng-click="sort_by_detail('promo_id')"><button class="sort_tool">Promo ID <span class="caret"></span></button></a></th>
						<th width="8%"><a ng-click="sort_by_detail('start_time')"><button class="sort_tool">Start <span class="caret"></span></button></a></th>
						<th width="8%"><a ng-click="sort_by_detail('end_time')"><button class="sort_tool">End <span class="caret"></span></button></a></th>
						<th width="8%" style="text-align:center"><a ng-click="sort_by_detail('jumlah_voucher')"><button class="sort_tool">Vouchers <span class="caret"></span></button></a></th>
						<th width="8%" style="text-align:center"><a ng-click="sort_by_detail('jumlah_redeem')"><button class="sort_tool">Redeems <span class="caret"></span></button></a></th>
						<th width="8%" style="text-align:center"><a ng-click="sort_by_detail('total_claim');"><button class="sort_tool">Claims <span class="caret"></span></button></a></th>
						<th width="8%" ><a ng-click="sort_by_detail('last_redeem_time');"><button class="sort_tool">Last Redeem <span class="caret"></span></button></a></th>
						<th width="8%" style="text-align:center"><a ng-click="sort_by_detail('minutes');"><button class="sort_tool">Minutes <span class="caret"></span></button></a></th>					
						<th width="8%"><a ng-click="sort_by_detail('redeem_ratio');"><button class="sort_tool">Redeem Ratio <span class="caret"></span></button></a></th>					
						<th width="8%"><a ng-click="sort_by_detail('claim_ratio');"><button class="sort_tool">Claim Ratio <span class="caret"></span></button></a></th>					
					</tr>
					</thead>				
					<tbody scroll>
						<tr ng-repeat="x in filtered_detail = ( search_list_detail | filter:query_detail) | orderBy:predicate_detail:reverse_detail ">
							<td width="300px" ng-bind-html="trustHtml(x.merchant)"></td>
							<td width="8%" ng-bind-html="trustHtml(x.promo_name)"></td>
							<td width="8%">{{ x.promo_id }}</td>
							<td width="8%">{{ x.start_time | asDate | date:'dd MMM yyyy HH:mm' }}</td>
							<td width="8%">{{ x.end_time | asDate  | date:'dd MMM yyyy HH:mm'}}</td>
							<td width="8%" align='center'>{{ (x.jumlah_voucher == null) ? 0 : x.jumlah_voucher | number:0  }}</td>
							<td width="8%" align='center'>{{ (x.jumlah_redeem == null) ? 0 : x.jumlah_redeem | number:0  }}</td>
							<td width="8%" align='center'>{{ (x.total_claim == null) ? 0 : x.total_claim | number:0  }}</td>
							<td width="8%" >{{ (x.last_redeem_time == null || x.last_redeem_time.trim() == '') ? '-' : x.last_redeem_time | asDate | date:'dd MMM yyyy HH:mm'  }}</td>
							<td width="8%" align='center'>{{ (x.minutes == null) ? '-' : x.minutes }}</td>
							<td width="8%" align='center'>{{ x.redeem_ratio = (x.jumlah_redeem/x.jumlah_voucher * 100) | number:2}} %</td>
							<td width="8%" align='center'>{{ x.claim_ratio = (x.total_claim/x.jumlah_voucher * 100) | number:2}} %</td>
						</tr>
					</tbody>
				</table>
			</div>		
			<div class="bg-loading">
				<div class="loading-text">
					<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="25px" height="25px"/>  &nbsp; &nbsp; <b>Loading...</b>
				</div>
			</div>
			<center>
			<div class="bg-sub-loading" style="display:block;">
				<div class="loading-text">
					<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="75px" height="75px"/><br/><h3><b>Loading...</b></h3>
				</div>
			</div>
			</center>
			</div>
			
			</div>
		</div>
		</div>
	</div>
	</div>
	<!-- Cover -->
	<div class="cover"></div>
	</body>	
</html>
<?php echo $this->inlineScript()->appendFile($this->baseUrl."/js/productggi/promo_amount.js"); ?>
