<?php echo $this->doctype();?>
<html ng-app="appFavourite">
<head>
	<?php echo $this->headTitle();?>
	<?php echo $this->render("includes/script.phtml"); ?>
</head>
<body class="bd_g_slime bd_slime_favourite" ng-controller="favouriteCtrl">
	<?php echo $this->render("includes/header.phtml"); ?>
	<?php echo $this->render("includes/hidden.phtml"); ?>
	<div class="ch-container">
		<div class="row">
			<!-- left menu starts -->
			<?php echo $this->render("includes/menu.phtml"); ?>
			<div id="content" class="col-lg-12 col-sm-12 push">
				<?php
					$category = $this->generate($this->config->param->gen->BOOKTYPE, array("cat" => $this->param->cat, "config" => $this->config));
					$crumb = array("Home" => $this->baseUrl,
									"S Lime" => "active",
									"Publication Download &nbsp;<strong>".$category."</strong>" => "active");
					$array = array(
									"item" => $crumb,
									"class" => "col-lg-7",
									"style" => "padding-right:0px"
									);
					echo $this->generate($this->config->param->gen->BREADCRUMB, $array);
				?>

				<div class="col-lg-5" id="search-crumb" style="padding-left:0px;">
					<div class="col-lg-8 pull-right" id="search_container" style="padding-right:0px; padding-left:5px;">
					<form action="<?php echo $this->baseUrl;?>/favourite" method="GET" role="form" id="search-form">
						<div class="input-group">
							<span class="input-group-btn">
								<button type="button" class="btn btn-default search-btn" type="button" id="advanced_search_button">
									<span class="caret"></span><span class="sr-only">Toggle Dropdown</span>
								</button>
							</span>
							<input type="text" class="form-control" placeholder="Search..." name="search" id="input_search" value="<?php echo $this->param->search;?>">
							<span class="input-group-btn">
								<button class="btn btn-default" type="submit" ><span class="glyphicon glyphicon-search"></span></button>
							</span>
						</div><!-- /input-group -->
					</form>
					</div><!-- /.col-lg-4 col-lg-push-4-->
			
					<div class="btn-group pull-right" id="export_csv">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
							<span class="glyphicon glyphicon-folder-open"></span> &nbsp; Export CSV  &nbsp;&nbsp; <span class="caret"></span>
						</button>
						<ul class="dropdown-menu" role="menu">
							<li><a ng-click="exportCurrent($event)" >Export Current Document</a></li>
							<li><a ng-click="exportAll($event)">Export All</a></li>
						</ul>
					</div>
					
				</div>
				<div class="col-sm-6" >			
					<div class="advanced_search_container col-sm-8" id="advanced_search_container">
						<div class="panel panel-default">
						<div class ="panel-body" >
							<h3>Advance Search</h3><hr/>
							<form action="<?php echo $this->baseUrl;?>/favourite" method="GET" role="form" class="form-horizontal">
							<div class="form-horizontal">
							<div class="advanced-input-group">
							<div class="form-group">
								<label for="inputEmail3" class="col-sm-3 control-label">Publication name</label>
								<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" placeholder="Title" name="title" id="title" value="<?php echo $this->param->title;?>">
								</div>
							</div>
							<div class="form-group">
								<label for="inputEmail3" class="col-sm-3 control-label">Publisher</label>
								<div class="col-sm-9">
								<input type="text" class="form-control advanced-input" placeholder="Publisher" name="publisher" id="publisher" value="<?php echo $this->param->publisher;?>">
								</div>
							</div>
							<button type="submit" class="btn btn-primary search-btn pull-right"><i class="glyphicon glyphicon-search"></i> &nbsp;Search</button>
							</div>
							</div>
							</form>
						</div>
						</div>
					</div>
			
				</div>
				<div class="col-sm-12">
					<div class="panel panel-default">
					<div class="panel-body">
						<div class="form-group pull-left form-inline">
							<form class="form-inline" role="form">
								<span class="pull-left lbl"><h5>&nbsp; <i class="glyphicon glyphicon-eye-open"></i> &nbsp;Showing &nbsp;<strong>{{favouriteList.length | number:0}}</strong>&nbsp; from 
								&nbsp;<strong>{{totalData | number:0}}</strong>&nbsp; data</h5></span>
							</form>
						</div>
				
						<div class="form-group pull-right form-inline">
							<div class="form-group ">
								<div class="input-group ">
								  <div class="input-group-addon">
									<span class="glyphicon glyphicon-filter"></span>&nbsp;&nbsp;<span class="badge">{{filtered.length | number:0}}</span>
									</div>
								  <input class="form-control" ng-model="query[queryBy]" placeholder="Filter by..." value="<?php echo $this->param->search;?>">
								</div>
							</div>
							<div class="form-group">
								<select class="form-control" ng-model="queryBy">
									<option value="$">All</option>
									<option value="title_name">Publication name</option>
									<option value="publisher_name">Publisher</option>
								</select>					
							</div>
						</div>
					</div>
					<div class="tb-test">
						<table class="table table-striped trans" id="transaction_table">
							<thead>
								<tr>
									<th width="55px" style="text-align:center;">No. </th>
									<th width="50%"><a href="#" ng-click="predicate='title_name' ; reverse=!reverse"><button class="sort_tool">Publication Name <span class="caret"></span></button></a></th>
									<th width="35%"><a href="#" ng-click="predicate='publisher_name' ; reverse=!reverse"><button class="sort_tool">Publisher <span class="caret"></span></button></a></th>
									<th width="12%" style="text-align:center;"><a href="#" ng-click="predicate='jumlah' ; reverse=!reverse"><button class="sort_tool">Total Download <span class="caret"></span></button></a></th>
								</tr>
							</thead>
							<tbody scroll>
								<tr ng-repeat="data in filtered=(favouriteList| filter:query ) | orderBy:predicate:reverse ">
									<td width="60px" align="center">{{$index+1}}.</td>
									<td width="50%"><a class="cursor" ng-click="searchDetail($event,data)" data-toggle="modal" ng-bind-html="trustHtml(data.title_name)"></a></td>
									<td width="35%">{{data.publisher_name}}</td>
									<td width="12%" align="center"><a href="<?php echo $this->baseUrl;?>/download?product={{data.title_name}}" target="_new"><strong>{{data.jumlah | number:0}}</strong></a></td>
								<tr>
							</tbody>
						</table>
					</div>
					<div class="bg-loading">
						<div class="loading-text">
						<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="25px" height="25px"/>  &nbsp; &nbsp; <b>Loading...</b>
						</div>
					</div>	
					
					<center>
					<div class="bg-log-loading" style="display:block">
						<div class="loading-text">
							<img src="<?php echo $this->baseUrl;?>/assets/images/gray75_polling.gif" width="75px" height="75px"/><br/><h3><b>Loading...</b></h3>
						</div>
					</div>
					</center>
					<div class="modal fade" id="magazineContent">
						<div class="modal-dialog" style="width:1000px">
							<div class="col-md-12 modal-content">
								<h3>
									<i class="glyphicon glyphicon-book"></i> &nbsp;Content Download
									<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
								</h3>
								<hr>
								<div style="">
									<table class="table table-striped">
										<thead>
											<tr>
												<th><a href="#" ng-click="predicate_c='title_name + release_date' ; reverse_c=!reverse_c"><button class="sort_tool">Edition <span class="caret"></span></button></a></th>
												<th style="text-align:center"><a href="#" ng-click="predicate_c='jumlah' ; reverse_c=!reverse_c"><button class="sort_tool">Total Download <span class="caret"></span></button></a></th>
											</tr>
										</thead>
										<tbody>
											<tr ng-repeat="x in detail | orderBy:predicate_c:reverse_c">
												<td>{{x.title_name + " - " + (x.release_date | asDate | date:'dd MMM yyyy')}}</td>
												<td align="center">{{x.jumlah}}</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>
<?php
echo $this->inlineScript()->appendFile($this->baseUrl."/js/slime/favourite.js");
?>
	
