<!-- Detail Pop Up -->
<!-- Product Box -->
<div class="modal fade" id="detailBox">
  <div class="modal-dialog" style="width:900px">
	<div class="modal-content">
		<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h3>&nbsp;<span class="glyphicon glyphicon-book"></span> &nbsp;Order Detail</h3>
		</div>
		
		<div class ="modal-body border-top-blue" >
		<div class="form-horizontal">
			<form role="form">
			 <div class="promo_content" >
				<div style="border: thin solid #ccc; border-radius:3px;padding-top:7px;padding-bottom:14px;">
				<div class="form-group">
					<label class="col-sm-3 control-label" for="inputEmail3">Order ID</label>
					<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{detailData.order_id}}</label>
				</div>
				<div class="form-group">
					<label class="col-sm-3 control-label" for="inputEmail3">Order Date</label>
					<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{detailData.order_date | asDate | date:'dd MMM yyyy HH:mm:ss'}}</label>
				</div>
				<div class="form-group">
					<label class="col-sm-3 control-label" for="inputEmail3">Customer</label>
					<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{detailData.name}} <strong>( {{detailData.email}} )</strong></label>
				</div>
				
				<div class="form-group">
					<label class="col-sm-3 control-label" for="inputEmail3">Order Total</label>
					<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{detailData.order_total | number:0}}</label>
				</div>
				
				<div class="form-group">
					<label class="col-sm-3 control-label" for="inputEmail3">Transaction ID</label>
					<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{ (detailData.transaction_id == null) ? '-' : detailData.transaction_id}}</label>
				</div>
				<div class="form-group">
					<label class="col-sm-3 control-label" for="inputEmail3">Payment Type</label>
					<label class="col-sm-9 control-label no-bold" for="inputEmail3"><capital>{{ (detailData.payment_type == null) ? '-' : detailData.payment_type.replace('_',' ')}}</capital></label>
				</div>
				<!--<div class="form-group">
					<label class="col-sm-3 control-label" for="inputEmail3">Masked Card</label>
					<label class="col-sm-9 control-label no-bold" for="inputEmail3" style="word-break:break-all;"><capital>{{ (callback.masked_card == null) ? '-' : callback.masked_card }}</capital></label>
				</div>-->
				<div class="form-group">
					<label class="col-sm-3 control-label" for="inputEmail3">Payment Time</label>
					<label class="col-sm-9 control-label no-bold" for="inputEmail3">{{ (callback.transaction_time == null) ? '-' : (callback.transaction_time | asDate | date:'dd MMM yyyy HH:mm') }}</label>
				</div>
				<div class="form-group">
					<label class="col-sm-3 control-label" for="inputEmail3">Payment Status</label>
					<label class="col-sm-9 control-label no-bold" for="inputEmail3"><capital>{{ (callback.fraud_status == null) ? '-' : callback.fraud_status }}</capital></label>
				</div>
				<!--<div class="form-group">
					<label class="col-sm-3 control-label" for="inputEmail3">Signature Key</label>
					<label class="col-sm-9 control-label no-bold" for="inputEmail3" style="word-break:break-all;"><capital>{{ (callback.signature_key == null) ? '-' : callback.signature_key }}</capital></label>
				</div>-->
				<div class="form-group">
					<label class="col-sm-3 control-label" for="inputEmail3">Status Message</label>
					<label class="col-sm-9 control-label no-bold" for="inputEmail3" style="word-break:break-all;"><capital>{{ (callback.status_message == null) ? '-' : callback.status_message }}</capital></label>
				</div>
				
			   </div>
			   
			   <div class="bar-notice" role="alert" ng-class="{'bar-yellow':detailData.status == 'pending', 'bar-green': detailData.status=='completed', 'bar-red' : detailData.status=='expired'}">
					Transaction is <strong>{{detailData.status}}..</strong>
			   </div>
			   
			   <div class="form-group" ng-show="filter_detail.length > 0" style="background-color:#ddd;margin-top:20px !important;padding-bottom:8px;">
					<label class="col-sm-3 control-label" for="inputEmail3"><span class="glyphicon glyphicon-tag"></span> &nbsp;Products</label>
					<label class="col-sm-9 control-label no-bold" for="inputEmail3"></label>
				</div>
				<div class="form-group" ng-show="filter_detail.length > 0">
					<div class="order-detail-box"   >
			   
						<div class="card-box" ng-repeat="data in filter_detail = (detail | filter:'SINGLE_PRODUCT')">
							<img ng-if="data.cover == null || data.cover'.trim() == ''" src='<?php echo $this->baseUrl;?>/assets/images/no_image.jpg' style='border-bottom:thin solid silver;' width="250px"/>
							<img  ng-if="data.cover != null && data.cover.trim() != ''" src='http://s-lime.com/static/public/{{data.cover}}' style='border-bottom:thin solid silver;' width="250px"/>
							<div class="div-bottom-box">
								<strong>{{data.product_name + data.bulan}}</strong>
								<div style="margin-top:3px;margin-bottom:3px;font-size:10pt;">
								{{ (data.synopsis) ? 'Release date : ' + (data.release_date | asDate | date:'dd MMM yyyy'): data.synopsis}}
								</div>
								<span class="label label-primary" style="margin-top: 24px;">
									{{data.author}}
								</span>
							</div>
							
							<div class="div-mini-bottom-box" style="border-top:thin solid silver;">
								Price : {{data.product_price | number:0}},-
							</div>
						</div>
					</div>
				</div>

				<div class="form-group" ng-show="filter_pck.length > 0"  style="background-color:#ddd;margin-top:20px !important;padding-bottom:8px;">
					<label class="col-sm-3 control-label" for="inputEmail3"><span class="glyphicon glyphicon-tags"></span> &nbsp;Packages</label>
					<label class="col-sm-9 control-label no-bold" for="inputEmail3"></label>
				</div>

				<div class="form-group" ng-show="filter_pck.length > 0" >
					<div class="panel panel-default" style="margin-top:18px" ng-repeat="data in filter_pck = (detail | filter:'PACKAGE')">
					  <div class="panel-body">
					  	<table class="col-lg-12">
					    	<tr>
					    		<td width="65%">
					    			<strong><capital>{{data.product_name}}</capital></strong>
					    		</td>
					    		<td width="35%">
					    			<div class="div-mini-bottom-box">
					    				Price : {{data.product_price | number:0}},-
					    			</div>
					    		</td>
					    	</tr>
						</table>
					  </div>
					</div>
				</div>
			</form>
		</div>
		</div>
	</div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->